### ISSUE TITLE
Get error: build 18963 or newer is required - my version is 10.0.18363.1198

### ISSUE THREAD

**Issue by JamieRCHI** [thebookisclosed/ViVe#10]
Microsoft Windows [Version 10.0.18363.1198]
I have my Windows Pro set up so updates don't happen unless I want them to happen.
It has been only a couple of months since I last updated. (I feel like I am in confession. :) )

Seems to me this should not happen.
Edit1: Upgraded Windows just now to Microsoft Windows [Version 10.0.18363.1316]
Still not working. Trying to run this to get rid of the Rewards thing in the main Setups page.
vivetool addconfig 19638787 1
Still get this response on Administrator command prompt:
Windows 10 build 18963 or newer is required for this program to function

**Comment by thebookisclosed** [comment]
There are much newer Windows releases out there than 1909 which you are currently running. ViVe is compatible with versions 2004 and newer.
If you don't want to upgrade, check out github.com/riverar/mach2. Mach2 is like ViVe except it utilizes the older feature control APis.

**Comment by JamieRCHI** [comment]
Thanks. 
I was only looking at the build number which according to the error build 18963 was required (or newer) which to me says that this build was ok. 
Maybe the error response should say "Windows build higher than 18963 is required ...". I think the error response message is misleading or incorrect.
And maybe the error code should mention the Windows 10 version number in addition to the build number?

I had to go into the Group Policy to force an upgrade to 20H2 for some strange reason. Apparently others have had issues where they were stuck on 1909.

**Comment by thebookisclosed** [comment]
Please read carefully. 18963 is not 18363.
