### ISSUE TITLE
Is it possible that one feature doesn't depend on another feature?

### ISSUE THREAD

**Issue by Dhyfer1** [thebookisclosed/ViVe#100]
Hi @thebookisclosed 👋

Thanks for your help on my issue #56, now I need your help again.

As you have seen in my previous issue, I wanted to disable the native file explorer tabs permanently, and it works when I use the command `vivetool /disable /id:37634385`, and my file explorer after using the command looks like this:

![image_3](https://github.com/thebookisclosed/ViVe/assets/50301201/8cd13e80-7608-44f7-b001-f01188d5053d)

Now, it is possible to activate a header UI for the file explorer using the command `vivetool /enable /id:40950262` and I was guided by this [article](https://geekermag.com/how-to-enable-windows-11-file-explorer-redesign-2023/). But first I will show you how the file explorer appears (with tabs enabled) before using the command:

![image_8](https://github.com/thebookisclosed/ViVe/assets/50301201/1256e9b7-bb38-420f-8e4c-9253de2b5103)

And after using the command it appears like this:

![image_10](https://github.com/thebookisclosed/ViVe/assets/50301201/69a2ce0e-e2e4-4924-84bb-5380bcb8b4ef)

I like the new address bar and search box with rounded corners, plus the new location for the action buttons and I want to have these features in the file explorer without tabs. Now, taking into account this third image, I use vivetool to disable the tabs with the first command I mentioned (with the id:37634385), and then I restart but after logging in and opening the file explorer, it appears the same as in the first image, no rounded corners for the address bar/search box and the action buttons are still in the same position as before.

What I was hoping, (after enabling the command with the id:40950262 to enable the header UI, and disabling the id:37634385 command to disable the native tabs), was that my file explorer might look like this (edited image):

![Untitled](https://github.com/thebookisclosed/ViVe/assets/50301201/d9e22568-c3eb-43d4-8608-f31c3d095fc1)

But as I said before, even after using the command to activate the header UI and disable the native tabs, my file explorer appears the same as in the first image, even when the command `vivetool enable /id:40950262` is still active.

Apparently, the new header UI only works when the file explorer has native tabs enabled, it is as if these two commands I mentioned are somehow linked, as if one depends on the other to work. Is that possible? Can they disassociate? Is there any way that the new header UI can be displayed in the file explorer without tabs? Because I would like my file explorer to look like the last image.

My problem occurs in Windows 11 Pro. Dev Channel. Latest build 23466.1001. Version 22H2. Latest version of ViveTool.

**Comment by thebookisclosed** [comment]
Feature dependencies are baked into binaries and there are no easy means for discovering them other than manual reverse engineering at the moment. Given what you're describing the FEMNB feature does most likely depend on TIFE and there's no way to change that.

**Comment by Dhyfer1** [comment]
Oh, what a pity, :( I really wanted my file explorer to look like in the last image. That's ok, it's not possible at the moment. Thanks for replying.
