### ISSUE TITLE
RGB controller error

### ISSUE THREAD

**Issue by nickmalbsn** [thebookisclosed/ViVe#102]
i downloaded the v0.3.3 version of vive and i input this command: cd c:\folder\path\ViveTool-v0.x.x then i input this command: vivetool /enable /id:35262205 and then i got this error: The image file is valid, but is for a machine type other than the current version. Please help!

**Comment by RyanLua** [comment]
> cd c:\folder\path\ViveTool-v0.x.x

Have you tried changing this path to be the folder containing ViVeTool? Example: `cd C:\Users\YOUR_USER_HERE\Downloads\ViVeTool-v0.3.3`

**Comment by thebookisclosed** [comment]
Why did you download the arm64 version even though you aren't using this architecture? That's the only way to end up with this error. Download the other zip.
