### ISSUE TITLE
Machine type Mismatch

### ISSUE THREAD

**Issue by sreyaz01** [thebookisclosed/ViVe#105]
![image](https://github.com/thebookisclosed/ViVe/assets/13959463/cb7752ad-0957-44a9-9d53-37dc1647a79e)

![image](https://github.com/thebookisclosed/ViVe/assets/13959463/b5080b2b-a343-4833-b09e-c544596a5e49)

**Comment by thebookisclosed** [comment]
Don't download the arm64 version, you're clearly not on an arm64 PC if that error appears.
