### ISSUE TITLE
not a valid application for this OS platform

### ISSUE THREAD

**Issue by dualglass** [thebookisclosed/ViVe#106]
PS C:\Users\dburns> c:\vivetool\vivetool /enable /id:44774629,44850061,44776738,42105254,41655236
Program 'ViVeTool.exe' failed to run: The specified executable is not a valid application for this OS platform.At
line:1 char:1
+ c:\vivetool\vivetool /enable /id:44774629,44850061,44776738,42105254, ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ c:\vivetool\vivetool /enable /id:44774629,44850061,44776738,42105254, ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

running:
OS Name	Microsoft Windows 11 Pro for Workstations Insider Preview
Version	10.0.23493 Build 23493

**Comment by flyoffacliff** [comment]
Same issue, on a fresh install.

**Comment by thebookisclosed** [comment]
Please just read the architecture label. Is that so much to ask? Don't download the arm64 ZIP if you aren't on an ARM64 machine.

**Comment by dualglass** [comment]
AMD64 and Intel 64 are essentially the same architecture. AMD originally developed the 64-bit extension to the x86 architecture and called it AMD64. Later, Intel adopted the same architecture and called it Intel 64 (formerly known as Intel EM64T or IA-32e). Both AMD64 and Intel 64 are compatible with each other and provide the same 64-bit capabilities.

The reason for the different names is mainly due to branding and marketing strategies. AMD64 refers to the architecture as developed by AMD, while Intel 64 refers to the same architecture as implemented by Intel.

Despite the different names, software and operating systems that support AMD64 will generally also support Intel 64, and vice versa. This compatibility between AMD and Intel 64-bit processors allows users to run the same 64-bit software on either platform without issues. As a result, the terms AMD64 and Intel 64 are often used interchangeably to describe the 64-bit x86 architecture.

**Comment by flyoffacliff** [comment]
They said ARM64, not AMD64. Big difference
