### ISSUE TITLE
ViVeTool not working on build 21354

### ISSUE THREAD

**Issue by RGarrido03** [thebookisclosed/ViVe#11]
Hi! ViVeTool isn't working on build 21354, it runs but none of the feature IDs are being applied. On previous Dev builds it was working. Do you want any logs? Thanks.

**Comment by thebookisclosed** [comment]
21354 is a release branch build. Release branches usually take feature control almost entirely away from the user and hardcode feature states inside system files.

**Comment by RGarrido03** [comment]
Oh sorry, I didn't know that! Thank you!

**Comment by thebookisclosed** [comment]
I'll add a disclaimer about release branch feature locks into the next version. Wish I had thought of this a bit sooner, I imagine there are a few more confused people.

**Comment by hpwamr** [comment]
> `Win10 v21H2 Dev Insider Build 21390` too!

PS: If needed, can I help you test the beta versions with my Laptop Win10 Dev 21H1 (just contact me at this [address](mailto:hpwamr51@gmail.com)) ? 🤔
