### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by Dan-Essin** [thebookisclosed/ViVe#111]
Hello,
I installed this on one Win 11 machine this am and it worked fine. 
I installed it on a second Win 11 machine this pm. When I try to run it a window flashes on the screen momentarily and then vanished.

No Idea what's going on here.
Does anyone have any thoughts?

**Comment by thebookisclosed** [comment]
You are probably mixing up the unofficial GUI and the official CLI projects. You're supposed to use this from the command line.
