### ISSUE TITLE
I can't open Windows Explorer because of two disabled features.

### ISSUE THREAD

**Issue by Dhyfer1** [thebookisclosed/ViVe#113]
Hi @thebookisclosed 👋

In the latest Windows 11 dev build 23545.1000, I have used Vivetool to disable tabs and the new File Explorer header UI using these commands: `vivetool /disable /id:37634385,40950262`

But first, I show you the query before making any changes to these two id's

```
[37634385] (TIFE)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[40950262] (FEMNB)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)
```

Then I run the command: `vivetool /disable /id:37634385,40950262` and after reboot, this is the new query

```
[37634385] (TIFE)
Priority        : User (8)
State           : Disabled (1)
Type            : Override (0)

[40950262] (FEMNB)
Priority        : User (8)
State           : Disabled (1)
Type            : Override (0)
```
This is the problem. After disabling the above two id's, I can't open file explorer. When I click the file explorer icon on the taskbar or call it with Win+E, my PC screen goes black for a second and then the desktop restarts on its own, but the file explorer does not open. This did not happen to me in previous dev builds, as I already showed you in [100#issue](https://github.com/thebookisclosed/ViVe/issues/100#issue-1735392046).

And if I want to use the file explorer again, I have to use the /reset or /fullreset commands from vivetool.

As you can see in the second query, both id's are disabled, but I can't open file explorer to see the changes. I'm sure if I could open file explorer with these two features disabled, then I would be able to see it without tabs and without the new header UI, which is what I want.

This problem also happens even in a reinstallation of Windows 11 from scratch and deactivating the two mentioned id's.

Any solution for this?

Edit: I have also tried disabling only one id at a time and then restarting my PC. When I deactivate only the id 40950262 (which is responsible for the new UI header), after the reboot, the file explorer can open and it appears with the tabs and without the new UI header.

But when I disable only the id 37634385 (which is responsible for the tabs) and restart, file explorer does not open.

Before deactivating just one id at once, I have used the `vivetool /fullreset` command.

**Comment by thebookisclosed** [comment]
Hi,
I don't have any advice on what to do other than *don't do this*

Figuring out a proper way to disable these (if there even is one) implies sinking a decent chunk of time into reverse engineering Explorer internals which is way out of scope of this issue tracker. You wouldn't ask the author of Regedit why particular registry edits make the system act weird -- all they do is provide you with an interface and have no easy oversight over how the data you put in gets used.
