### ISSUE TITLE
NoNewAppAlert

### ISSUE THREAD

**Issue by merlin555** [thebookisclosed/ViVe#114]
Hello everyone,

Is it possible to influence the “**NoNewAppAlert**” with “**ViVeTool**” ?
Unfortunately, the registry no longer works under Windows 11.
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer
"NoNewAppAlert"

This entry in the registry prevents Windows 10
from that, a message does not always appear when it asks for the standard shortcut of a program.
This message keeps coming until you click "always allow." prevents.

Since I made a batch file myself, where all the program links are located.
Unfortunately, I still don't have the option under Windows 11, to stop this annoying message forever.

Greetings,

Merlin

**Comment by thebookisclosed** [comment]
Requesting OS component reverse engineering for the purpose of finding feature IDs is way out of scope of this issue tracker.

**Comment by merlin555** [comment]
Thanks for your answer.
I figured it out.
In Windows 11, don’t just register the entry once.

HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v "NoNewAppAlert" /t REG_DWORD /d "1" /f
HKLM\SOFTWARE\Richtlinien\Microsoft\Windows\Explorer" /v "NoNewAppAlert" /t REG_DWORD /d "1" /f
HKLM\SOFTWARE\WOW6432Node\Policies\Microsoft\Windows\Explorer" /v "NoNewAppAlert" /t REG_DWORD /d "1" /f
HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer" /v "NoUseStoreOpenWith" /t REG_DWORD /d "1" /f
