### ISSUE TITLE
Disabling Tabs in the File Explorer

### ISSUE THREAD

**Issue by jed84** [thebookisclosed/ViVe#115]
ViveTool 0.3.3 allowed to disable the Tabs in the File Explorer by executing the following commands:

```
vivetool /disable /id:36354489
vivetool /disable /id:37634385
vivetool /disable /id:39145991
```

This no longer works on Windows 11 23H2 (22621.2361) and executing the above codes will result in the File Explorer crash.

Looking fo a way to fix it and disable tabs in the File Explorer.

**Comment by momoca** [comment]
me too +1

**Comment by jed84** [comment]
I have run the following:
```
vivetool /enable /id:39145991
vivetool /disable /id:37634385
vivetool /disable /id:36354489
```
and this disabled the tabs in the FIle Explorer correctly.

However, there is another problem as the Command Bar does no longer follow the theme of the system, so items are not readable:
![obraz](https://github.com/thebookisclosed/ViVe/assets/47121522/2b2687e5-5e0e-4b14-af03-b2129a3adfbb)

So now, once thr tabs are disabled, I am looking for a way to fix the colour of the Command Bar.

**Comment by momoca** [comment]
> I have run the following:
> 
> ```
> vivetool /enable /id:39145991
> vivetool /disable /id:37634385
> vivetool /disable /id:36354489
> ```
> 
> and this disabled the tabs in the FIle Explorer correctly.
> 
> However, there is another problem as this breaks the colour of the Command Bar. In the result the items are not readable: ![obraz](https://user-images.githubusercontent.com/47121522/271123063-2b2687e5-5e0e-4b14-af03-b2129a3adfbb.png)
> 
> So now, once the tabs are disabled, I am looking for a way to fix the colour of the Command Bar.

Problems Also not resolved

**Comment by ppp-coder** [comment]
How about this?
https://windows-waza.com/how-to-disable-and-restore-tabs-in-windows-11-explorer/

**Comment by thebookisclosed** [comment]
Please don't use the issue tracker as a forum for finding workarounds to permanent feature state changes in updates.

**Comment by AndroidDeveloperLB** [comment]
About the colors, you can use this:
https://github.com/MicaForEveryone/MicaForEveryone

Sadly the disabling of tabs seem to have caused issues for me yesterday, after I've updated to :
"2024-01 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5034204)" 

The issue is that I couldn't start Explorer at all. Nothing happened.
I had to use system restore. 
Can anyone confirm about this?

**Comment by Dhyfer1** [comment]
> I have run the following:
> ```
> vivetool /enable /id:39145991
> vivetool /disable /id:37634385
> vivetool /disable /id:36354489
> ```
> and this disabled the tabs in the FIle Explorer correctly

U still have tabless explorer?
