### ISSUE TITLE
code needed for virtual desktop thingy

### ISSUE THREAD

**Issue by N0tBLUE** [thebookisclosed/ViVe#116]
does anybody knows the code for desktop switching hover notification we get after switching virtual desktop 

![image](https://github.com/thebookisclosed/ViVe/assets/74755694/3e451b5a-aa6e-4b57-9870-c032081f0df7)

**Comment by thebookisclosed** [comment]
Random areas of the OS don't just magically contain feature IDs that disable elements you don't like.

**Comment by xStrom** [comment]
That notification is bundled with `34508225` and `40459297` might also be related. A restart is needed for it to take effect.
