### ISSUE TITLE
The 'livetool' item cannot be recognized as the name of a Cmdlet, function, script file, or executable program. 

### ISSUE THREAD

**Issue by BlueCat-TY** [thebookisclosed/ViVe#117]
The 'livetool' item cannot be recognized as the name of a Cmdlet, function, script file, or executable program. Please check the spelling of the name, if it includes a path, make sure the path is correct, and then try again.

**Comment by thebookisclosed** [comment]
Spelling the program name correctly would be a great start...

**Comment by BlueCat-TY** [comment]
Suggestion [3,General]: 找不到命令 ViVeTool.exe，但它确实存在于当前位置。默认情况下，Windows PowerShell 不会从当前位置加载命令。如果信任此命令，请改为键入“.\ViVeTool.exe”。有关详细信息，请参阅 "get-help about_Command_Precedence"。
-----------
使用以下命令使其成功：PS D:\test> .\ViVeTool.exe /enable /id:29785186
