### ISSUE TITLE
OS Build Incompatibility

### ISSUE THREAD

**Issue by INeedHelP2007** [thebookisclosed/ViVe#118]
### Tool version

0.3.3

### OS version

Windows 11 Education Build 22621.2428 Version 22H2

### Architecture

x64

### Screenshot

![image](https://github.com/thebookisclosed/ViVe/assets/79464101/5b9edc6f-1090-49a1-922d-b3d2be485ff5)

"This version of C:\zVIVE\ViVeTool.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher."

Compatibility says that you need have Windows 10 build 18963 or newer. And that's exactly what I have, so I don't understand why it isn't working. I've also watched several tutorials how to use ViveTool

### Extra steps

None

**Comment by thebookisclosed** [comment]
You downloaded the arm64 ZIP. Your PC is not arm64.
