### ISSUE TITLE
Vive Tool not working

### ISSUE THREAD

**Issue by Valsisttv** [thebookisclosed/ViVe#119]
### Tool version

ViVeToolv0.3.3

### OS version

Windows 11, version 23H2

### Architecture

x64

### Screenshot

I followed the steps on how to properly install ViVeTool in order to get the various transparency settings for the Taskbar however, even after following the commands needed in command prompt in admin mode, ViVe tool doesnt work. 
The icon doesnt even show up in TaskBar in order for me to change from the various settings.

### Extra steps

Tried the same install option twice after restarting

**Comment by thebookisclosed** [comment]
As far as I know there are no features which control a taskbar's transparency. I don't think you're using this correctly, and even if such features have been recently added, they may not be supported by the build you're running. You didn't even specify which commands you ran...
