### ISSUE TITLE
not compatible with this version of Windows

### ISSUE THREAD

**Issue by Azeiynali** [thebookisclosed/ViVe#121]
### Tool version

0.3.3

### OS version

windows 11 22H2 build 22621.2715

### Architecture

x64

### Screenshot

>>vivetool
This version of C:\Windows\System32\ViVeTool.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

### Extra steps

None

**Comment by dzid26** [comment]
make sure you download non- ARM version
