### ISSUE TITLE
windows 11 21h2 compatibility issue

### ISSUE THREAD

**Issue by improbir** [thebookisclosed/ViVe#123]
### Tool version

v0.3.3

### OS version

Windows 11 22000.2538

### Architecture

x64

### Screenshot

![image](https://github.com/thebookisclosed/ViVe/assets/25155316/62615d54-4adc-49fb-85f4-157ad0578822)

### Extra steps

vivetool /disable /id:40430431

**Comment by improbir** [comment]
![image](https://github.com/thebookisclosed/ViVe/assets/25155316/79213d5f-0c11-472f-be0a-a53f59e252f1)

**Comment by Overruler** [comment]
![Screenshot (154)](https://github.com/thebookisclosed/ViVe/assets/3786941/4157477e-52af-43e7-bcbb-7bea2205ae07)
This can be caused by trying to run the ARM binary on an Intel desktop processor.
