### ISSUE TITLE
While applying the new Start menu layout, I got this error

### ISSUE THREAD

**Issue by TotallyNotPooh** [thebookisclosed/ViVe#126]
### Tool version

v0.3.3

### OS version

Windows 11 build 22635.3420

### Architecture

x64

### Screenshot

![image](https://github.com/thebookisclosed/ViVe/assets/123549284/4ef3ce3c-128f-4f3e-bbbc-b708eb242096)

### Extra steps

None

**Comment by thebookisclosed** [comment]
Hi, sorry for such a super late reply. Are you still having this Access denied issue?
