### ISSUE TITLE
Can no longer disable "42354458,34508225,40459297"

### ISSUE THREAD

**Issue by YingDoge** [thebookisclosed/ViVe#128]
### Tool version

0.3.3

### OS version

Version	10.0.22631 Build 22631

### Architecture

x64

### Screenshot

That i  tryied to turn it off after few trys it just doenst work. 
Any help please thansk

### Extra steps

s

**Comment by YingDoge** [comment]
Hide/Remove virtual desktop indicator while changing
https://superuser.com/questions/1800216/windows-11-hide-remove-virtual-desktop-indicator-while-changing?newreg=254206bc0b8848a09f48cd6b606dafed

**Comment by ryan-preble** [comment]
Having the same issue. @YingDoge's answer did not work. This happened immediately after installing 2024-04 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5036980)

**Comment by thebookisclosed** [comment]
It would be great if you read the text that appears before you file an issue..

> In case you've followed a tutorial for toggling features and didn't get the desired result, this is most likely NOT a bug.
Similarly, do NOT file a bug if a feature can't be toggled anymore after updating. Once Microsoft finishes experimenting with a feature it gets put into a permanently Enabled or Disabled state which ViVe can't change anymore.

I can't do anything about it.

**Comment by YingDoge** [comment]
> Having the same issue. @YingDoge's post is what should work, but just doesn't anymore. This happened immediately after installing 2024-04 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5036980)

you can uninstall the update. i am trying rihgt now

**Comment by YingDoge** [comment]
> Having the same issue. @YingDoge's post is what should work, but just doesn't anymore. This happened immediately after installing 2024-04 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5036980)

2024-04 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5036980) yes it wokred
