### ISSUE TITLE
Classic File Explorer Windows 11 23H2 ID

### ISSUE THREAD

**Issue by azza19861** [thebookisclosed/ViVe#130]
### Tool version

v0.3.3

### OS version

Windows 11 23H2 22631.3593

### Architecture

x64

### Screenshot

With the latest update of Windows 11 23H2 build 22631.3593 (kb5037771).  We used to disable ID's 40950262,41076133 which reverted the file explorer to the classic version with the ribbon.  After this update the above ID's don't work.  

### Extra steps

none

**Comment by thebookisclosed** [comment]
Please read the bug filing template before filing a bug...
It quite literally says
> In case you've followed a tutorial for toggling features and didn't get the desired result, this is most likely NOT a bug.
Similarly, do NOT file a bug if a feature can't be toggled anymore after updating. Once Microsoft finishes experimenting with a feature it gets put into a permanently Enabled or Disabled state which ViVe can't change anymore.
