### ISSUE TITLE
Will Not Work 

### ISSUE THREAD

**Issue by noformulahere** [thebookisclosed/ViVe#132]
### Tool version

0.3.3

### OS version

Windows 11 Pro build 22631.3880

### Architecture

x64

### Screenshot

I extract the file to system32 then run the command as admin and restart but nothing happens. I seen this and thought it would be a cool feature should i not waste my time?

### Extra steps

1) Download vivetool 0.3.3 
 2) Extract vivetool to system32 
  3) Run command vivetool /enable /id:34878152 as administrator 
   4) Restart computer

**Comment by thebookisclosed** [comment]
You should not be extracting anything to System32. The feature ID you mentioned might not be available in the build you're running anymore given you observed no changes after a reboot. There's nothing that can really be done
