### ISSUE TITLE
Windows lock screen stuck

### ISSUE THREAD

**Issue by Ahoura-Bagherfar** [thebookisclosed/ViVe#133]
### Tool version

v0.0.3

### OS version

Windows 11 build 26252.5000

### Architecture

x64

### Screenshot

Hi I enabled all flags
After restarting Windows, the lock screen freezes, only the mouse can be moved. How can I return the flags to the default mode?

### Extra steps

.

**Comment by Ahoura0** [comment]
The problem is with the flags, but I don't know which one.  Before signing in, the charger (probably any device) should not be connected to the laptop

**Comment by Ahoura-Bagherfar** [comment]
The problem is with the flags, but I don't know which one.  Before signing in, the charger (probably any device) should not be connected to the laptop
