### ISSUE TITLE
An error occurred while setting feature configurations in the Runtime store (Access is denied)

### ISSUE THREAD

**Issue by xyzedn** [thebookisclosed/ViVe#134]
### Tool version

v0.3.3

### OS version

Windows 11 build 26120.961

### Architecture

x64

### Screenshot

![image](https://github.com/user-attachments/assets/79f16de7-78f8-4303-bbac-b2c335e679bd)

### Extra steps

1) Run /enable /id:39007349
2) Run /enable /id:48433719

**Comment by miaosen** [comment]
run the terminal as administrator
