### ISSUE TITLE
0.3.3 Ne Phone Sidebar feature not working

### ISSUE THREAD

**Issue by bathtimethiago** [thebookisclosed/ViVe#135]
### Tool version

0.3.3

### OS version

Windows 11 Pro build 22635.4076

### Architecture

x64

### Screenshot

![image](https://github.com/user-attachments/assets/c5b84ed0-cd1f-47e2-a97c-847013f1379b)

### Extra steps

/enable /id:48433719,48697323

**Comment by bathtimethiago** [comment]
says it was active but nothing changes

**Comment by thebookisclosed** [comment]
Not a tool bug, this feature has more dependencies than just feature IDs.
