### ISSUE TITLE
The feature is not enabled even by giving a successful message

### ISSUE THREAD

**Issue by ghost1372** [thebookisclosed/ViVe#136]
### Tool version

v0.3.3

### OS version

26100

### Architecture

x64

### Screenshot

![image](https://github.com/user-attachments/assets/880d015d-07a1-4695-97e4-d3de722c537c)

### Extra steps

i am using new 24h2 windows 11 (26100) and i want to enable id:45130483 
`vivetool /enable /id:45130483`
i get successful message, but when i search for query `vivetool /query` i am see this message:

```
[45130483]
Priority        : User (8)
State           : Enabled (2)
Type            : Experiment (1)
PayloadKind     : External (2)
Payload         : 0x0

[45130483]
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)
PayloadKind     : Resident (1)
Payload         : 0x32
```

**Comment by thebookisclosed** [comment]
The feature is enabled, multiple configurations can exist for the same feature, the highest priority is what ends up being used.
