### ISSUE TITLE
KB5004296 disables ViveTool v0.2.1

### ISSUE THREAD

**Issue by crim2som** [thebookisclosed/ViVe#14]
Other Updates: 2021-07 Cumulative Update Preview for Windows 10 Version 21H1 for x64-based Systems (KB5004296) Successfully installed on 31/07/2021 has disabled ViveTool v0.2.1

ViveTool v0.2.1 is applied within Local Admin account, but this 21H1 Other Updates has now completely disabled its function.  Will there be an update? Regards.

**Comment by alwaysaheadofMS** [comment]
I updated a client's computer and could remove the stupid advertising as well. It doesn't pay to update machines to the latest updates because of these reasons! Windows 10 is fantastic keeping viruses off the machines!!

**Comment by crim2som** [comment]
Hi @alwaysaheadofMS 

It is not easy when MS bloatware does not have option to toggle off/on. This banner is very large and not wanted. Very pleased that ViveTool v0.2.1 was working. 

I also have Malwarebytes. Hackers are always finding ways to circumvent Windows 10 x64. Windows version 21H1 security is not dealing with all the virus vulnerabilities.

**Comment by alwaysaheadofMS** [comment]
Hi@crim2som please let me know if anyone fixes this issue, I get tired of these monkeys and their manipulations!

**Comment by alwaysaheadofMS** [comment]
> Hi @alwaysaheadofMS
> 
> It is not easy when MS bloatware does not have option to toggle off/on. This banner is very large and not wanted. Very pleased that ViveTool v0.2.1 was working.
> 
> I also have Malwarebytes. Hackers are always finding ways to circumvent Windows 10 x64. Windows Security version 21H1 is not dealing with all the virus vulnerabilities.

Hi@crim2som please let me know if anyone fixes this issue, I get tired of these monkeys and their manipulations!

**Comment by thebookisclosed** [comment]
This problem is less misleadingly described by issue #15
