### ISSUE TITLE
Problème d'éxecution de Vive Tool

### ISSUE THREAD

**Issue by ManuelOGER** [thebookisclosed/ViVe#18]
Bonjour,
Je n'arrive pas à exécuter Vive Tool j'ai déjà essayé en tant d'Administrateur elle s'ouvre et se referme automatiquement.

Comment faire ?

Pour info mon ordinateur à Windows 11 installé récemment.

Merci de votre aide

**Comment by Shaughn-david** [comment]
Open cmd then cd into the folder that vivetool is located in then run vivetool from there

**Comment by thebookisclosed** [comment]
ViVeTool is a command line tool. You have to use it from the Command Prompt.
