### ISSUE TITLE
Error occurred while setting a live feature configuration

### ISSUE THREAD

**Issue by EnhancedJax** [thebookisclosed/ViVe#19]
Currently on windows insider build 22572.100 ni_release, trying to activate the new file explorer tabs feature but got this error instead.

![image](https://user-images.githubusercontent.com/80020581/158009044-02aa0f05-bdf5-497d-9bde-71189030e0db.png)

**Comment by Shaughn-david** [comment]
Try running ViVeTool as admin.

**Comment by EnhancedJax** [comment]
Thanks. This worked!
