### ISSUE TITLE
Vivetool is not working.

### ISSUE THREAD

**Issue by User9993459** [thebookisclosed/ViVe#2]
Vivetool is not working on Windows 10 build 20150 and all other previous builds. I use the program as told but changes never show up. I deleted the task (ReconcileFeatures) in taskplanner to prevent Windows from going back to the default and still nothing works.

I do not understand what I am doing wrong.

**Comment by RokeBeedell** [comment]
I too have not been able to run ViveTool either for a reason that I am unaware of.
### System information
- [DESKTOP-D6C6GAB.txt](https://github.com/thebookisclosed/ViVe/files/4887302/DESKTOP-D6C6GAB.txt)
- [DxDiag.txt](https://github.com/thebookisclosed/ViVe/files/4887303/DxDiag.txt)

**Comment by thebookisclosed** [comment]
I will be looking into potential rollback inducing issues in the coming days

**Comment by thebookisclosed** [comment]
Issues of similar character will be consolidated into #6
