### ISSUE TITLE
Multi tabs works in Build 19044.1586..??

### ISSUE THREAD

**Issue by zerocoolroot** [thebookisclosed/ViVe#20]
Hi, 

Firstly, thank you so much by your great job..!!

Sorry my bad english..!!

Multi tabs works in Build 19044.1586..?? I tried in this Build and doesn't work for me..!!

I put the two files into folder C\Windows\System32.

I opened the CMD as Administrator and I wrote the command below:
vivetool addconfig 34370472 2

Thanks in advance..!!

**Comment by WindowsShadows** [comment]
Multi tabs **OBVIOUSLY** won't work in that build. They're only in 22557.

**Comment by johnef** [comment]
I have a newer build but didn't work for me
My windows is 11 build 22579

**Comment by thebookisclosed** [comment]
Each build has its own feature configuration, IDs won't magically bring features from a new version to an old one, nor will they bring old canceled or compiled out features into new builds.
