### ISSUE TITLE
ViVeTool and Windows 10 settings banner

### ISSUE THREAD

**Issue by rob-daneel** [thebookisclosed/ViVe#21]
Hello,

I have Windows 10 version 21H2 (build 19044.1586) with Windows Feature Experience Pack 120.2212.4170.0 installed on my PC. Until now I was be able to disable the Settings App banner with the following commands

.\vivetool.exe addconfig 18299130 1
.\vivetool.exe addconfig 31950543 1

After installing the following Windows updates:

KB4023057
KB5011487

the previous commands have no effect. Is there any way to restore the previous behavior?

Thanks in advance for any reply.

**Comment by Svk1190** [comment]
I am facing the same issue, the settings banner returned with the latest update.

**Comment by xcasxcursex** [comment]
Same here. Vivetool seems to be completely broken, the changes are confirmed but not present. From an admin powershell prompt:

```
PS C:\_Build\OS\Windows> ./ViVeTool.exe addconfig 18299130 1
ViVeTool v0.2.1 - Vibranium feature configuration tool

Successfully set feature configuration
PS C:\_Build\OS\Windows> ./ViveTool.exe addconfig 31950543 1
ViVeTool v0.2.1 - Vibranium feature configuration tool

Successfully set feature configuration
PS C:\_Build\OS\Windows> .\ViVeTool.exe /querysubs
ViVeTool v0.2.1 - Vibranium feature configuration tool

PS C:\_Build\OS\Windows> .\ViVeTool.exe /queryconfig
ViVeTool v0.2.1 - Vibranium feature configuration tool

PS C:\_Build\OS\Windows>
```

Good thing I won't be putting up with this much longer, I'm ditching this garbage OS for linux.

**Comment by ujdastack** [comment]
Very easy

go to settings, go to time and language, go to region, and  select "country or region" to "China"

No need to reboot, your ugly settings banner is gone!


You can try other countries, some show 1 icon, some show 3 icons, but after I have tried more than 20, I found only China f**ked Microsoft so hard, Microsoft has to remove this ugly settings banner.

**Comment by spec1re** [comment]
@ujdastack 

lol this works! any side effect setting china here in EU?

**Comment by Mitradis** [comment]
@spec1re Edge now with chinese news lol. And some setup installers use chinese. Not good solution.

**Comment by ImSpecial** [comment]
funny, but not really a solution, is there any update to this? "Officially".

**Comment by thebookisclosed** [comment]
ViVeTool exists purely to alter the state of specific configurable features in a build of Windows. Microsoft changing or removing specific configurable IDs does not fall in scope of ViVe support.

**Comment by ImSpecial** [comment]
Is the problem that this is no longer a Windows configurable feature, or was the special ID number for it changed?

**Comment by thebookisclosed** [comment]
It can no longer be configured whatsoever.

**Comment by ImSpecial** [comment]
Wow that really sucks! :/

**Comment by xcasxcursex** [comment]
> It can no longer be configured whatsoever.

It was good while it lasted, thanks mate.

**Comment by Cowering** [comment]
> Very easy
> go to settings, go to time and language, go to region, and select "country or region" to "China"
> 
> You can try other countries, some show 1 icon, some show 3 icons, but after I tried more than 20 countries, I found only China f**ked Microsoft so hard, Microsoft has to remove this ugly settings banner for China.

Hilarious! Works for me, and I deleted unused language packs while there and my installers now only see 'English', no Chicom gibberish

**Comment by alwaysaheadofMS** [comment]
> > Very easy
> > go to settings, go to time and language, go to region, and select "country or region" to "China"
> > You can try other countries, some show 1 icon, some show 3 icons, but after I tried more than 20 countries, I found only China f**ked Microsoft so hard, Microsoft has to remove this ugly settings banner for China.
> 
> Hilarious! Works for me, and I deleted unused language packs while there and my installers now only see 'English', no Chicom gibberish

Thanks so much "Cowering", that worked on my system too. You're the only person on the internet that has found the solution to this MS crap. I did it on my personal machine but not 100% sure if I dare use that trick on customers business pc's as we don't know if the region is set to China, if it will have any weird ramifications in other areas. But I love it on my own pc, thanks again!

**Comment by bpcw** [comment]
Not sure if setting your "country or region" to China just to get rid of the settings header is such a good idea. China is very special in many respects when it comes to software legislation, and you may end up crippling your Windows installation or getting some unwanted features.
As much as I loathe the settings header, I'd rather live with it than make such a potentially grave change to my system config.
After initial configuration, I usually don't fire up the settings app all too often anyway.

**Comment by alwaysaheadofMS** [comment]
> Very easy
> 
> go to settings, go to time and language, go to region, and select "country or region" to "China"
> 
> No need to reboot, your ugly settings banner is gone now!
> 
> You can try other countries, some show 1 icon, some show 3 icons, but after I tried more than 20 countries, I found only China f**ked Microsoft so hard, Microsoft has to remove this ugly settings banner for China.
 @ujdastack,  works for me too. Such a simple fix!!!

**Comment by Cowering** [comment]
Well, the China hack looked OK, but after a few minutes of sitting in any menu (like power & sleep), it goes back to 'Home' even if the 'App Banner' now has anything to show. I manually switch from 20 minutes to 1 minute for screen blanking so my concentration is not broken when looking at code, but I still save a little energy otherwise.

**Comment by alwaysaheadofMS** [comment]
> Well, the China hack looked OK, but after a few minutes of sitting in any menu (like power & sleep), it goes back to 'Home' even if the 'App Banner' now has anything to show. I manually switch from 20 minutes to 1 minute for screen blanking so my concentration is not broken when looking at code, but I still save a little energy otherwise.

My laptop has been on for 24 hours, no problems.

**Comment by elderlabs** [comment]
My Surface runs Win10 21H2 build 19044.1836. There is no settings banner. Any chance I can assist in diagnosing the reason mine is hidden? Perhaps I may be of assistance for others. The Surface was originally installed with 20H1, then upgraded to 21H2 over time with NTlite. If the banner is still gone for me, surely there's a means of doing the same for others. I've also never used a tool to remove the banner. It was never there to begin with.

**Comment by bpcw** [comment]
> My Surface runs Win10 21H2 build 19044.1836. There is no settings banner. Any chance I can assist in diagnosing the reason mine is hidden? Perhaps I may be of assistance for others. The Surface was originally installed with 20H1, then upgraded to 21H2 over time with NTlite. If the banner is still gone for me, surely there's a means of doing the same for others. I've also never used a tool to remove the banner. It was never there to begin with.

Are you certain about the build number 19044.18**36**, or is this a typo? So far, the following versions (starting July 12 2022) seem to be available:

- 10.0.19044.1826 (KB5015807) 
- 10.0.19044.1862 (KB5015878)
- 10.0.19044.1865
- 10.0.19044.1889 (KB5016616)

The only version of Windows that I positively know does not have a settings banner is the Enterprise version of Win10, which I assume you don't have running on your Surface device?

If you happen to be on 10.0.19044.1826 with a Home or Pro version of Win10, I'd be very interested to learn why the settings header does not show up in your case. 

As other users found out, the appearance of the dreaded settings banner seems to be influenced by other variables (like regional settings). Maybe there are more conditions under which it won't show up?

Do you have any Windows settings (region, accessibility, ...) that an average user might not have?

**Comment by elderlabs** [comment]
Ah, so that explains it. I am in fact running Enterprise, and that was a typo in the build number. Perhaps there's another means of hiding it without running enterprise, or a way to trigger the hide variable. I suppose we could all dig a bit deeper, though gone are the days of user choice and deciding what's best for our hardware ourselves -- at least with Microsoft. Here I thought I'd found an edge case; while it _is_, it's not the one I'd hoped for.

**Comment by bpcw** [comment]
> Ah, so that explains it. I am in fact running Enterprise, and that was a typo in the build number. Perhaps there's another means of hiding it without running enterprise, or a way to trigger the hide variable. I suppose we could all dig a bit deeper, though gone are the days of user choice and deciding what's best for our hardware ourselves -- at least with Microsoft. Here I thought I'd found an edge case; while it _is_, it's not the one I'd hoped for.

I presume that the Enterprise version just gets a different set of .exe/.dll files, in which the whole header-related code is entirely absent.

**Comment by mark4picsdotcom** [comment]
I ran Vivetool.exe to enable Tabs in explorer .

✅ Commands to Enable:
vivetool /enable /id:37634385
vivetool /enable /id:39145991
vivetool /enable /id:36354489

Will this cause a conflict with Windows update? I didn't disable Vivetools before I updated widows to 22621.675
but I did disable vivetool  then rebooted, uninstalled 22621.675, rebooted, reinstalled 22621.675 rebooted**and had no tabs in explorer**

**Comment by xcasxcursex** [comment]
> I ran Vivetool.exe to enable Tabs in explorer .

This issue is about something else. Perhaps you should make a new one. Good luck with Explorer :)

**Comment by alwaysaheadofMS** [comment]
Whats the point of any of this useless shit, Microsoft restores their nagging settings after a few updates, you guys need a fucking job!
