### ISSUE TITLE
Vivetool does not seem to work Windows 11 ARM through Parallels on Macbook

### ISSUE THREAD

**Issue by leaflore** [thebookisclosed/ViVe#23]
After following the directions, the terminal windows states that it works, but after restarting the OS, I do not see the tabs on the file explorer.

**Comment by johnef** [comment]
Same here!

**Comment by thebookisclosed** [comment]
You're most likely running into overzealous feature state resetting found in recent Windows 11 builds, this will be addressed in an upcoming update.

**Comment by leaflore** [comment]
I did not update to latest release. I updated to newest version and the feature worked. But I think it stopped working temporarily.
