### ISSUE TITLE
Settings Header Banner Disabling

### ISSUE THREAD

**Issue by the-j0k3r** [thebookisclosed/ViVe#26]
I literally had this work once, until Windows was patched recently the header came back again and wont be disabled hidden anymore.

![Capture](https://user-images.githubusercontent.com/31389848/159639414-e90a7af8-6377-4ef3-a215-72094a69eff5.PNG)

Commands ran on admin powershell
```ps1
.\ViveTool.exe addconfig 18299130 1
.\ViveTool.exe addconfig 31950543 1
```

ViveTool Query all after reboot.
```ps1
> .\vivetool.exe queryconfig all
ViVeTool v0.2.1 - Vibranium feature configuration tool

[0x011738FA / 18299130]
Group: 4
EnabledState: Disabled (1)
EnabledStateOptions: 1
Variant: 0
VariantPayloadKind: 0
VariantPayload: 0

[0x016B553E / 23811390]
Group: 0
EnabledState: Enabled (2)
EnabledStateOptions: 0
Variant: 0
VariantPayloadKind: 0
VariantPayload: 0

[0x01A4258C / 27534732]
Group: 0
EnabledState: Disabled (1)
EnabledStateOptions: 0
Variant: 0
VariantPayloadKind: 0
VariantPayload: 0

[0x01E786CF / 31950543]
Group: 4
EnabledState: Disabled (1)
EnabledStateOptions: 1
Variant: 0
VariantPayloadKind: 0
VariantPayload: 0
```

Its shows 
`18299130` and `31950543` as disabled but the header is still visible

![Capture](https://user-images.githubusercontent.com/31389848/159640668-8fff5828-3fe4-41d3-8294-c4bb9e888bf4.PNG)

**Comment by the-j0k3r** [comment]
Ah should have read #21 

Microsoft, Oh Microsoft.

**Comment by the-j0k3r** [comment]
Worth noting that under `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FeatureManagement\Overrides\4`

neither of the configs added as above are listed.

![Capture](https://user-images.githubusercontent.com/31389848/159644876-2036761f-6148-49bb-82fe-514313c03fc3.PNG)

**Comment by alwaysaheadofMS** [comment]
It just happened on my main computer. I uninstalled the optional update  KB5011543 and the ads on the settings banner is gone again. It's an optional update so it won't automatically reinstall. I am on Win 10 Ver 21H2 build 19044.1387.

**Comment by the-j0k3r** [comment]
KB5011543 is some gimmick https://support.microsoft.com/en-us/topic/march-22-2022-kb5011543-os-builds-19042-1620-19043-1620-and-19044-1620-preview-4fe2d1c0-720f-47fe-9523-75339bc107a1

Search Highlights. Seriously? 

In any case I dont have that update installed.

![Capture](https://user-images.githubusercontent.com/31389848/159646934-f43f566e-7d35-4f41-aa0e-83a4aaab6e68.PNG)

**Comment by thebookisclosed** [comment]
> Worth noting that under `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FeatureManagement\Overrides\4`
> 
> neither of the configs added as above are listed.

Features stored in registry have IDs deliberately obfuscated, thank Microsoft. You can see the algorithm in ViVe's source.

**Comment by the-j0k3r** [comment]
Obfuscated is one thing, not showing up at all... didnt know they could do that.... see my screenshot above.

**Comment by thebookisclosed** [comment]
> Obfuscated is one thing, not showing up at all... didnt know they could do that.... [see my screenshot above.](https://github.com/thebookisclosed/ViVe/issues/26#issuecomment-1076007088)

There are 4 overrides visible in your queryconfig all output. There are 4 overrides in the registry screenshot. I don't see anything missing.
The IDs are obfuscated using this algorithm: https://github.com/thebookisclosed/ViVe/blob/master/ViVe/RtlDataHelpers.cs#L92

**Comment by the-j0k3r** [comment]
yea the numbers dont match with vivetools output at all comparing to screenshot.
