### ISSUE TITLE
能否关闭标签功能。

### ISSUE THREAD

**Issue by Zhuoershang** [thebookisclosed/ViVe#28]
由于兼容性问题，需要关闭已开启的标签功能

**Comment by Zhuoershang** [comment]
看到说明文件，del  可以删除

**Comment by Sciroccogti** [comment]
If you used `.\vivetool addconfig 34370472 2` to enable the feat, then you can try `.\vivetool delconfig 34370472 2` to disable it.

Also, you can use `.\vivetool queryconfig 34370472` to check if you have enabled the target feat.

**Comment by thebookisclosed** [comment]
Closing this issue as help was already provided and OP hasn't replied in a week.
