### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by Chaoschaot232** [thebookisclosed/ViVe#29]
Hi,

I tried this program out to get rid of this new pice of shitty Task Manager. I don't want it and decided to change it back to the old ones with the hope that on my Evaluation copy Build 22581.ni_release,220318-1623 this would work but it hasn't worked.

Used cmds: 
![image](https://user-images.githubusercontent.com/1703441/161427473-f25b8b19-3499-4664-9a2a-eeaec871a387.png)

Task Manger after using these cmds: 
![image](https://user-images.githubusercontent.com/1703441/161427490-b4e97ab5-15c6-447b-ade8-d630ff1d9f02.png)

Either things are not working here, or smth. is protecting the changes, which your program want's to do/to set or smth. else is not working.

Maybe it is better to get all relevant files from the old Taskmanger and simply overwrite them and compleatly remove the old files.

**Comment by thebookisclosed** [comment]
Please read through this new Wiki article to understand why you're experiencing the behavior you're describing:
https://github.com/thebookisclosed/ViVe/wiki/Which-features-can-ViVeTool-toggle%3F

**Comment by Chaoschaot232** [comment]
> Please read through this new Wiki article to understand why you're experiencing the behavior you're describing: https://github.com/thebookisclosed/ViVe/wiki/Which-features-can-ViVeTool-toggle%3F

So this means that the mentioned Feature IDs may have changed so that the commands itself are correct but the IDs aren't?
But why is the console then not erroring out? Shouldn't it blame for a non existing feature ID?

Tbh. I don't get it at all :S

**Comment by thebookisclosed** [comment]
Nowhere in that Wiki does anything say that IDs change. The shipping states do. They changed it from Disabled/Enabled By Default to Always Enabled, meaning you can't switch states anymore. The page also talks about IDs being decentralized and there being no way to guarantee that a change you've made results in a meaningful difference. Did you even read it?
