### ISSUE TITLE
Vivetool fails on Surface ProX

### ISSUE THREAD

**Issue by sa3eedo12** [thebookisclosed/ViVe#3]
When running vivetool addconfig 23615618 2, it returns error hr=0xc0000001.

**Comment by McBaumwolle** [comment]
I can confirm this, here is a screenshot. 
![image](https://user-images.githubusercontent.com/67203883/86511930-d1a74f80-bdfd-11ea-851f-9b41306109e3.png)

**Comment by thebookisclosed** [comment]
There are issues with internal structure layouts on architectures other than amd64, a version that works correctly on x86 and arm64 is in the works

**Comment by MattPeterUK** [comment]
Yes, thank you.

**Comment by matze19999** [comment]
@sa3eedo12 did you find a workaround to enable the new start menu?

**Comment by sa3eedo12** [comment]
@matze19999 not quite, I managed to get it after a few restarts. Didn't try restarting again though :p

**Comment by thebookisclosed** [comment]
This issue is fixed as of version 0.2.1
