### ISSUE TITLE
Enabling tabs on build 22598 doesn't work

### ISSUE THREAD

**Issue by Huligaan** [thebookisclosed/ViVe#31]
The ViVe Tool enable tabs doesn't work on this patch, atleast it doesn't for me. Is there a way to make it work?

**Comment by linkmadao** [comment]
Same thing here

**Comment by linkmadao** [comment]
> 

Same thing here

**Comment by thebookisclosed** [comment]
No. The build doesn't support this.
https://github.com/thebookisclosed/ViVe/wiki/Which-features-can-ViVeTool-toggle%3F
> Please do not create issues in the ViVe tracker if you ran into this scenario as it's not something that can be "fixed."
