### ISSUE TITLE
Vivetool 0.2.1 fails with Windows 11 Build 25115.1000

### ISSUE THREAD

**Issue by fgGitH2001** [thebookisclosed/ViVe#32]
See the error below when issuing ViveTool queryconfig all:

ViVeTool v0.2.1 - Vibranium feature configuration tool

Unhandled Exception: System.ArgumentException: Group must not be more than 14
   at Albacore.ViVe.FeatureConfiguration.set_Group(Int32 value)
   at Albacore.ViVe.RtlFeatureManager.QueryAllFeatureConfigurations(FeatureConfigurationSection section, UInt64& changeStamp)
   at Albacore.ViVeTool.Program.ProcessArgs(String[] args)
   at Albacore.ViVeTool.Program.Main(String[] args)

D:\ViVeTool>

![image](https://user-images.githubusercontent.com/104878161/168153133-c25b8c23-589e-456e-a308-edcc94832f8d.png)

Same problem with Build 22621 and 25115.

**Comment by fgGitH2001** [comment]
Same problem with Build 25126.1000.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/104878161/170411544-d665def7-85aa-4e11-af7d-3ea535dbe8b2.png">

<img width="564" alt="image" src="https://user-images.githubusercontent.com/104878161/170411609-6e852acf-53df-4c45-9b33-9c32977005a8.png">

**Comment by AHPanna** [comment]
i just rebuild with higher value of `group` parameters here: https://github.com/thebookisclosed/ViVe/blob/master/ViVe/FeatureConfiguration.cs#L37

download: https://etnaalternancenet0-my.sharepoint.com/:u:/g/personal/abdulh_p_etna-alternance_net/EWYPazwzl3tIoVQmMtapgMEBHdBbPazYEKUDILP7tE5pxw?e=vR3cnI


<img width="835" alt="image" src="https://user-images.githubusercontent.com/4123487/170679162-1cb1ce4d-d4a8-4c48-b497-86af31461e39.png">

**Comment by fgGitH2001** [comment]
Hello, How do I get the new Vivetool with the fix? I still see only the 0.2.1 from Aug 11, 2020. Will you make a new zip file with the fix?Thanks for your help.Regards, F.G.  Sent from Mail for Windows From: PrydazSent: Friday, May 27, 2022 3:08 AMTo: thebookisclosed/ViVeCc: fgGitH2001; AuthorSubject: Re: [thebookisclosed/ViVe] Vivetool 0.2.1 fails with Windows 11 Build 25115.1000 (Issue #32) i just rebuild with higher value of group parameters here: https://github.com/thebookisclosed/ViVe/blob/master/ViVe/FeatureConfiguration.cs#L37download: https://etnaalternancenet0-my.sharepoint.com/:u:/g/personal/abdulh_p_etna-alternance_net/EWYPazwzl3tIoVQmMtapgMEBHdBbPazYEKUDILP7tE5pxw?e=vR3cnI—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by fgGitH2001** [comment]
Thanks, I just downloaded the debug.zip and it worked with vivetool queryconfig all.
<img width="397" alt="image" src="https://user-images.githubusercontent.com/104878161/170782821-df7b5257-3d63-48d4-857f-e4309bd781b6.png">

**Comment by alwaysaheadofMS** [comment]
Is it possible to remove the advertising from the Settings Banner with the new vive tool? Thanks

**Comment by thebookisclosed** [comment]
> Is it possible to remove the advertising from the Settings Banner with the new vive tool? Thanks Win 10 ver 19044.1706

https://github.com/thebookisclosed/ViVe/issues/15#issuecomment-1133906711
No. Stop hijacking other open issue threads.

**Comment by alwaysaheadofMS** [comment]
> > Is it possible to remove the advertising from the Settings Banner with the new vive tool? Thanks Win 10 ver 19044.1706
> 
> [#15 (comment)](https://github.com/thebookisclosed/ViVe/issues/15#issuecomment-1133906711) No. Stop hijacking other open issue threads.

You can't beat Microsoft son, quit beating your head against a wall, foolishness! lol

**Comment by thebookisclosed** [comment]
This issue should be addressed by the newly released v0.3.0.
If similar problems arise, this thread can be reopened.
