### ISSUE TITLE
Feature store problems

### ISSUE THREAD

**Issue by dongle-the-gadget** [thebookisclosed/ViVe#39]
For some reason, the `/store` parameter is unrecognized in 0.3.0, despite being listed in `vivetool /enable /?`.
```
> vivetool /enable /id:37010913 /store:both

ViVeTool v0.3.0 - Windows feature configuration tool

Unrecognized parameter: /store

Successfully set feature configuration(s)
```

The help documentation:
```
> vivetool /enable /?

ViVeTool v0.3.0 - Windows feature configuration tool

Syntax:
  /enable [...] [/store:<both | runtime | boot>]

[...]
```

Secondly, features are not added to the "boot" store, despite `vivetool /enable /?` saying it does.
```
> vivetool /enable /id:37010913

ViVeTool v0.3.0 - Windows feature configuration tool

Successfully set feature configuration(s)
```
```
> vivetool /query /store:runtime /id:37010913

ViVeTool v0.3.0 - Windows feature configuration tool

[37010913]
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
```
```
> vivetool /query /store:boot /id:37010913

ViVeTool v0.3.0 - Windows feature configuration tool

No configuration for feature ID 37010913 was found in the Boot store
```
```
> vivetool /enable /?

[...]

The parameters in square brackets don't need to be specified and will use these defaults:
  [...]
  Store             : Both

[...]
```

**Comment by thebookisclosed** [comment]
The writes do go to both stores by default, the selector not working is a very dumb oversight on my part. Like the /? info says, "Writing to the Boot store is necessary for features to persist across reboots. Changes to this store become
effective the next time you reboot."
Did you reboot between running /enable and /query?

**Comment by dongle-the-gadget** [comment]
I thought that changes would be saved, and there would be a way to view saved features. Query only lists features that are enabled?

**Comment by dongle-the-gadget** [comment]
Alright, so problem 2 is intended behavior of ViVeTool, whereas problem 1 is an oversight.

**Comment by Muhammad11777** [comment]
How to use this on Windows 11?

**Comment by dongle-the-gadget** [comment]
Wdym by "using this on Windows 11"?

**Comment by Portkinov** [comment]
how to run this program?

**Comment by jaytoth** [comment]
Can I only enable tabs without the navigation pane?

**Comment by dongle-the-gadget** [comment]
Why is everyone spamming this thread with "how to use ViVeTool?"

**Comment by klisza1993** [comment]
i do, ive got 21h2 and none is working
