### ISSUE TITLE
Please add list/examples of known features

### ISSUE THREAD

**Issue by ericgl** [thebookisclosed/ViVe#40]
Hello,
It would be nice if you could add a few examples to the main page of several features which users might want to enable.
Right now all I see is a list of feature numbers (some have obscured names) with a state of either disabled or enabled.
If you already know what some of these features do, please share with us.

So, for example, if feature XXXXX enables dark mode for task manager in Windows 10, please tell us so.
Do I have to guess what each one does?

**Comment by thebookisclosed** [comment]
This is easier said than done, you have the FeatureDictionary.pfs file which has ID and name pairs, some names are fairly obvious while some are rather obscure.

**Comment by ericgl** [comment]
Well, I have seen someone suggest using the following codes for adding tabs in Win11 Windows Explorer:
**ViVeTool.exe addconfig 39145991 2
ViVeTool.exe addconfig 37634385 2
ViVeTool.exe addconfig 36354489 2**

Do you have other known-to-work examples?

**Comment by thebookisclosed** [comment]
This is like asking someone for worthwhile registry edits, it's all subjective and version dependent. Follow various Windows Insider communities to see which IDs do what and what builds they apply to. The purpose of this tool is to facilitate feature management, not to serve as a guide. There's a merit to there being a slight learning curve, with an overly simplified approach editing things you don't fully understand becomes too easy.

**Comment by ericgl** [comment]
Well, if anyone is interested, here is the registry location that the ViveTool affects:
**HKLM\SYSTEM\CurrentControlSet\Control\FeatureManagement\Overrides\4\XXXXXXXXXX**

It modifies the value "**EnabledState**" under those keys.
1 = Disabled, 2 = Enabled

Note that the IDs DO NOT correspond to the keys' names. And there's no description inside each key to understand what the override does. Annoying, but that's how Microsoft chose to do it. Obfuscate.
