### ISSUE TITLE
Windows 10 settings bar?

### ISSUE THREAD

**Issue by mixMugz** [thebookisclosed/ViVe#41]
Hi. This is not iisue repport, just for ask question. Is last version can turn off Windows 10 Setting Bar or still no success?

**Comment by dongle-the-gadget** [comment]
If you mean the bar in the image below, then no. The feature is now labeled as "Always Enabled", meaning ViVeTool won't be able to do anything.
<img width="754" alt="image" src="https://user-images.githubusercontent.com/29563098/177253553-26d0b077-fb84-4433-bec0-bf65be853ae9.png">

See #21

**Comment by mixMugz** [comment]
Oh. Got it. This is really suck.

**Comment by the-j0k3r** [comment]
This is strange. Very strange.

My Windows 10 Pro on Host, no longer can be disabled.

My Windows 10 Pro on a VM, I disabled this and it stuck, its not become visible again even past the upgrade from 20h2 to 21h1

**Comment by BlohoJo** [comment]
You might be able to get rid of the banner by checking to see if you have update KB5011543 installed, and if you do, uninstall it. It's one of Microsoft's many "gimmick" updates that adds something called "Search Highlights", whatever that is, something no one wants or will use.

**Comment by the-j0k3r** [comment]
No its not installed.

**Comment by BlohoJo** [comment]
I wonder if you could *force* it's install of the .msu from the Microsoft Update Catalog, then *uninstall* it.

Otherwise, the easiest thing to probably do is switch your Windows version to Enterprise. That will pretty surely get rid of it.

**Comment by the-j0k3r** [comment]
Right, neither VM nor host ever had it that KB, VM isn't Enterprise its just a regular pro version, Im just curious why one worked and stuck despite upgrades and the host doesn't. The only thing I can think of the the video from vm is virtualized virtualbox something.
