### ISSUE TITLE
FileExplorer's Tabs doesn't work on W11_22622.290

### ISSUE THREAD

**Issue by emilianocastelletta** [thebookisclosed/ViVe#44]
On my Windows11 build 22622.290 fileexplorer's tabs doesn't work.
Furthermore Explorer crashes if i open with WIN+E instead double click on "MyComputer".
Is my buold unsupported from vivetools?

**Comment by thebookisclosed** [comment]
Make sure to enable features NWMTest1 and TIFE, then reboot.
