### ISSUE TITLE
Windows 10 1803 Sets Feature

### ISSUE THREAD

**Issue by Xenzofq** [thebookisclosed/ViVe#45]
If you're not sure what I'm talking about read here: https://www.howtogeek.com/352109/how-to-use-sets-in-windows-10-to-organize-apps-into-tabs/

This feature was an A/B testing feature before the release of 1803. It was introduced around Build 17074. So is there anyway you can make ViVe's lowest required version Build 16299 (1709) so that all Insider Builds of 1803 can possibly enable this feature?

**Comment by thebookisclosed** [comment]
No.
