### ISSUE TITLE
Win11 22000.778 Tabs Not Working !

### ISSUE THREAD

**Issue by Syberoot** [thebookisclosed/ViVe#46]
Help if Something Going Wrong!!!
<img width="960" alt="Screenshot 2022-07-10 233232" src="https://user-images.githubusercontent.com/109040595/178158574-1b79bb88-0b5c-461d-97e5-0b845b1450b8.png">
<img width="173" alt="Screenshot 2022-07-10 233146" src="https://user-images.githubusercontent.com/109040595/178158575-74e34a7b-40de-4dbc-8db3-464c520337a0.png">

**Comment by httpsColon** [comment]
[23877894] (ScoobeOnLogonForUpgradedDevices)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
Variant         : 1
PayloadKind     : Resident (1)
Payload         : 8000e07

[25704915] (RebootDowntimeEstimate)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
Variant         : 1

[26008830] (STTest)
Priority        : ImageOverride (15)
State           : Disabled (1)
Type            : Override (0)

[34592303] (SuggestedActionsOnCopy)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[35620393] (OverflowPanel2)
Priority        : ImageOverride (15)
State           : Disabled (1)
Type            : Override (0)

[35681102] (DoNotUseForTesting)
Priority        : Service (4)
State           : Disabled (1)
Type            : Experiment (1)

[36828252]
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
Variant         : 1
PayloadKind     : Resident (1)
Payload         : 37

[37007953]
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[37337272] (SmartWorkflows)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[37634385] (TIFE)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[38320543] (SmartWorkflowsAugLoopTelemetry)
Priority        : ImageOverride (15)
State           : Disabled (1)
Type            : Override (0)

[38859191] (RedirectProgrammableTiles)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[38888144] (ASRTest)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[39145991] (NWMTest1)
Priority        : 1 (1)
State           : Enabled (2)
Type            : Override (0)

[39145991] (NWMTest1)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[39146010] (UxTest12)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[39177456] (MoreProgrammableSlotsInStart)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39281392] (MTestUx13)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

**Comment by httpsColon** [comment]
什么first issue 就直奔这里
