### ISSUE TITLE
Vivetool Feature Number

### ISSUE THREAD

**Issue by chiragnahata** [thebookisclosed/ViVe#49]
How to know which feature is in which id in Vivetool ?

**Comment by chiragnahata** [comment]
Please help. Please dont close the issue without resolution

**Comment by thebookisclosed** [comment]
There is no pretty dictionary with descriptions of which feature ID does what, these A/B flags were never officially documented by Microsoft.
All ViVe provides is a list of known IDs and their Class Names (brief names assigned my Microsoft themselves, often cryptic).
If you wish to learn more then follow various online Microsoft communities where enthusiasts figure out which features to enable or disable to achieve a desired result.

**Comment by 03302024** [comment]
Just for those who get here by googling: 

- vivetool /query command displays a list of detectable features and their status on your system
- FeatureDictionary.pfs file from ViVeTool is a list of all available feature IDs.

More info:

- [Unlock Hidden Windows Features with ViVeTool](https://www.tech2geek.net/unlock-hidden-windows-features-with-vivetool/)
- [Why isn't there a list of all of the features in Vivetool, & what they do?](https://www.elevenforum.com/t/why-isnt-there-a-list-of-all-of-the-features-in-vivetool-what-they-do.34189/)
