### ISSUE TITLE
Please help regarding update or uninstall this program.

### ISSUE THREAD

**Issue by subhajitnandi** [thebookisclosed/ViVe#5]

**Comment by AviHafner** [comment]
please try to use
ViVeTool.exe addconfig
you can see the parameter to Disabled
to Disabled run
ViVeTool.exe addconfig 23615618 2

**Comment by AviHafner** [comment]
please try to use
ViVeTool.exe addconfig
you can see the parameter to Disabled
to Disabled run
ViVeTool.exe addconfig 23615618 1

**Comment by thebookisclosed** [comment]
ViVeTool is a standalone program, that means it does not install or embed itself into your system in any way
If you wish to get rid of it you can simply delete it

If you'd like to get rid of existing feature configurations, please use the queryconfig command to discover them and then issue according delconfig commands
