### ISSUE TITLE
How to disable/ uninstall Vivetool

### ISSUE THREAD

**Issue by lmjaedentai** [thebookisclosed/ViVe#51]
My pc experienced `SYSTEM_THREAD_EXCEPTION_NOT_HANDLED` after installing this software. 
![IMG20220722154452_01](https://user-images.githubusercontent.com/63090071/180394897-cfbe892e-b8f2-4016-8d7b-fdfc7825e93d.jpg)

Thus I want to disable it. Thanks for any suggestions or solutions! 

- Vivetool version: the latest one
- Windows 11 22H2 (release preview)

**Comment by thebookisclosed** [comment]
ViVeTool is a portable program, no installation is required.
It's very unlikely that the changes you've made resulted in the blue screen above.
The only thing that can be done is resetting the state for the feature IDs/names you've altered, or performing a full reset if you've forgotten which one you changed.
