### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by crazybluegithub7** [thebookisclosed/ViVe#53]
when i try to change taskbar i restart file explorer and nothing changes, does anyone know how to fix this? im using Windows 11 21H2
image: https://user-images.githubusercontent.com/109390855/182002968-a20de6c3-faa4-420c-b341-cf0f8e2d9539.png

video download for proof of not working: https://www.mediafire.com/file/rl68i2ivuk8rxij/2022-07-30_20-17-20.mp4/file

**Comment by crazybluegithub7** [comment]
video download for proof: https://www.mediafire.com/file/rl68i2ivuk8rxij/2022-07-30_20-17-20.mp4/file

**Comment by crazybluegithub7** [comment]
video download for proof of not working: https://www.mediafire.com/file/rl68i2ivuk8rxij/2022-07-30_20-17-20.mp4/file

**Comment by crazybluegithub7** [comment]
when i said "im using Windows 11 21H" i ment to say "im using Windows 11 21H2" :c

**Comment by thebookisclosed** [comment]
The feature you're trying to alter is exclusive to Dev builds.
