### ISSUE TITLE
Make a feature change permanent

### ISSUE THREAD

**Issue by temis01** [thebookisclosed/ViVe#54]
<img width="957" alt="Explorer opened with own icon" src="https://user-images.githubusercontent.com/75322684/182792754-e181b4bd-7df9-482f-92af-27385a7b7fa2.png">
This is not really an issue but I'd like to change a feature's parameters and I haven't found instructions yet :

In windows 22h2 beta build 22622.450 the tabbed explorer is on but nav pane shows libraries twice.

I managed to turn explorer nav pane back to normal by applying :  vivetool /disable /id:36354489 /store:both

but after rebooting once or twice duplicate libraries are back again.

Is there a way to make that command (vivetool /disable /id:36354489 /store:both) permanent ?

Thanks for your help.
Temis

PS:

- Feature state when nav pane has duplicate libraries rebooting after the insiders "upgrade" or after vivetool command:
(cf picture) 

[36354489] (SV2Navpane)
Priority        : Service (4)
State           : Enabled (2)
Type            : Override (0)

- Feature state before doing anything with vivetool (fresh from enrolling windows insider "upgrade") :
In this state nav pane is OK until next reboot.

[36354489] (SV2Navpane)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)

- Feature state after applying the command and rebooting :
In this state nav pane is OK until next reboot.

[36354489] (SV2Navpane)
Priority        : Service (4)
State           : Disabled (1)
Type            : Override (0)

**Comment by temis01** [comment]
M$ is apparently actively working on the problem since build 25174 in dev channel.
Hopefully the patch will also reach beta ... soon

see in known issues / explorer :
https://www.neowin.net/news/windows-11-dev-build-25174-brings-multiple-file-explorer-fixes-and-improvements/

**Comment by thebookisclosed** [comment]
Further issues with persistence across reboots will be tracked in #56
