### ISSUE TITLE
Can't enable bluetooth menu

### ISSUE THREAD

**Issue by smalex-z** [thebookisclosed/ViVe#55]
Not sure if it's a problem on my part or the program, but I first tried to enable the bluetooth menu by using the following commands in an administrator command prompt: 
`vivetool addconfig 35221101 2`
`vivetool addconfig 29881313 2`

I saw that it was moved to /enable instead, so I tried the following, which appeared to go through fine in the command prompt and enabled the features, but nothing changed in the windows UI:
`vivetool /enable /id:35221101`
`vivetool /enable /id:29881313`

That did nothing so I tried 
`vivetool /enable /id:35221101 /variant:2`
`vivetool /enable /id:29881313 /variant:2`

In the end the /enable commands say set feature configurations, and /query shows that they are changed, but nothing in the bluetooth menu has changed, even after computer/windows explorer restart. Am I doing the codes wrong? I got the original addconfig command from outdated tutorial videos of how to install the menu (from March 2022)

Thank you!

**Comment by thebookisclosed** [comment]
Make sure you're using a new enough build for these feature IDs to be supported, the commands you're executing are correct. (No need for /variant:2)

**Comment by smalex-z** [comment]
Build as in Windows build? My current build is the most recent version of Windows 11, so I don't know why the menu is not working. Pressing bluetooth doesn't bring up the quick connect menu, only toggles bluetooth on and off.

Do you have any advice on why it might be like this?

Again, thanks for this great program!

**Comment by ItzYuku** [comment]
I have the same issue and I cant figure it out

**Comment by thebookisclosed** [comment]
What is "the most recent version of Windows 11"?
Post the build number.

**Comment by smalex-z** [comment]
Version 21H2 OS Build 22000.856

**Comment by thebookisclosed** [comment]
That explains it. You're running a build that does not support this feature. Build ~22557 or newer is required.
