### ISSUE TITLE
Old version worked but Lastest is not

### ISSUE THREAD

**Issue by dateno1** [thebookisclosed/ViVe#57]
ViVeTool.exe addconfig 25175482 1
with 0.2.1 is worked

but
.\ViVeTool.exe /enable /id:25175482
with 0.3.1 is not work

Windows 10 22H2 (19044) x64 ko-KR

**Comment by thebookisclosed** [comment]
That's because 1 is disable and not enable.

**Comment by dateno1** [comment]
> That's because 1 is disable and not enable.

Almost software is '1' is 'enable', '0' is 'disable'.

OK I will test again today

**Comment by thebookisclosed** [comment]
If you read the description for addconfig in previous releases where these numerical values were used you would see that this is a Microsoft provided enum where 0 is Default, 1 is Disabled and 2 is Enabled. This is not my own design choice.

**Comment by dateno1** [comment]
Suggestion : Can you add 'example usage' on 'readme.md'?

User can find syntax by '/?' switch but I think it is always need

**Comment by thebookisclosed** [comment]
I'm thinking about creating Wiki pages so stuff isn't cramped inside Readme.md, but ultimately yes, more documentation is being considered.

**Comment by dateno1** [comment]
Work tested

v0.3.1 with '/disable' worked
