### ISSUE TITLE
TASKBAR Blank and not working

### ISSUE THREAD

**Issue by ChickChuck2** [thebookisclosed/ViVe#60]
after a windows update my start menu partially disappeared With the new right-click W11 options menu

![Screenshot_1](https://user-images.githubusercontent.com/48648882/187800219-4df8171d-0311-41aa-993d-43f9b44b6822.png)
![Screenshot_2](https://user-images.githubusercontent.com/48648882/187800234-55000a5b-8d77-4ad7-8b0b-b89c930db70b.png)

Note: Universal Windows Platform Apps Don't work anymore

I've already tried:
 vivetool.exe /disable /id39751186 /store:both
 vivetool.exe /fullreset
  
  Reinstall Windows 11 with InPlace Update
 Specs:
  Windows 11 Pro
  21H2
  Installed on 08/31/22
  OS: 22000.318
  
  I've tried create new user, the taskbar came as windows 10 style, but don't work
  
  UPDATE:
   after logout the new user the UWP apps work. and right click too
UPDATE 2:
 the taskbar worked when i restart the process "wsappx" on every windows startup

**Comment by ChickChuck2** [comment]
I fixed it by installing some random apps that modifies the taskbar to see if some settings would go back to default.

**Comment by thebookisclosed** [comment]
This does not appear to be a ViVe issue.
