### ISSUE TITLE
Problem for install 

### ISSUE THREAD

**Issue by MrFlappy0** [thebookisclosed/ViVe#63]
An error occurred while setting feature configurations in the Runtime store (Accès refusé)
please help meeeeee

**Comment by spierrard** [comment]
i have the same error with version 3.3.1

**Comment by MrFlappy0** [comment]
> i have the same error with version 0.3.1

Yes me to ): i don't understand

**Comment by thebookisclosed** [comment]
You're most likely using a production build where running as administrator is necessary for the program to function. If you can't make sense of simple Access denied errors then please avoid tinkering with features.
