### ISSUE TITLE
Cannot set PayloadKind and Payload

### ISSUE THREAD

**Issue by boe323** [thebookisclosed/ViVe#64]
Can you please add the ability to set these flags please

**Comment by thebookisclosed** [comment]
Can you please describe the commands you've tried which did not update these fields? I didn't have issues with updating these when testing.

**Comment by thebookisclosed** [comment]
Tested and couldn't reproduce the issue. Perhaps you were confused by the shortened name (VariantPayloadKind -> PayloadKind) when printing feature properties to the console on `/query`? Unifying these may not be a bad idea but the shorter name in console was chosen deliberately for ease of reading.
