### ISSUE TITLE
Remove left margins in Explorer for the "List" view

### ISSUE THREAD

**Issue by destinyhammer** [thebookisclosed/ViVe#68]
Hello!

In 22H2 weird left margins appeared when the list view selected. Is it possible repair this with the ViveTool? In previous versions of Windows 11 it looked fine.
![image](https://user-images.githubusercontent.com/37699848/197335404-ac5e59c8-143d-484f-aed5-af794069804b.png)

**Comment by thebookisclosed** [comment]
Please don't use this issue tracker for feature research requests. ViVe is merely a tool for toggling feature states, the consequences of said toggles are out of scope.
