### ISSUE TITLE
Get the current state of the ID

### ISSUE THREAD

**Issue by sanmaodo** [thebookisclosed/ViVe#71]
Thank you for such a great tool.

I have a question:
How to query the current state of an id, whether it is on or off ?

**Comment by sanmaodo** [comment]
What I want to say is, how to get the "Feature State" data in the picture below：

<img width="548" alt="Feature State" src="https://user-images.githubusercontent.com/29154707/198955786-19fc07b4-b402-414d-a15a-bae68199e48f.png">

**Comment by thebookisclosed** [comment]
You can use `vivetool /query /id:39130896` for example. The tool is jam packed with information on how to use it, just read through it.

**Comment by sanmaodo** [comment]
@thebookisclosed 
Thank you, and powerful ViVe !
