### ISSUE TITLE
Remains from the default file explorer

### ISSUE THREAD

**Issue by Moise368** [thebookisclosed/ViVe#73]
After installing the new Windows11 tabs using:

vivetool /enable /id:37634385
vivetool /enable /id:39145991
vivetool /enable /id:36354489

I have this from the old File Explorer still there:
![image](https://user-images.githubusercontent.com/73934891/204042066-0560e674-a539-465b-aaa6-e87c6999f296.png)

I installed this feature before and I had no problems until now.

**Comment by thebookisclosed** [comment]
I believe this was a known bug in builds with tabbed File Explorer back in November, does it still happen to you?
