### ISSUE TITLE
ViveTool /resetall not reseting all settings to stock even after reboot.

### ISSUE THREAD

**Issue by myn** [thebookisclosed/ViVe#75]
ViveTool /resetall doesn't reset all of my settings to stock even after reboot when I execute a vivetool /query

ViVeTool v0.3.2 - Windows feature configuration tool

[26008830] (STTest)
Priority        : ImageOverride (15)
State           : Disabled (1)
Type            : Override (0)

[34592303] (SuggestedActionsOnCopy)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[35620393] (TOTest)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[37007953] (PATKTI)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[37337255] (SmartClipboardUX)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[37337272] (SmartWorkflows)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[37634385] (TIFE)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[37715785] (ProfileDataRoamingClient11x11)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[38320543] (SmartWorkflowsAugLoopTelemetry)
Priority        : ImageOverride (15)
State           : Disabled (1)
Type            : Override (0)

[38758896] (BSFUPP)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[38764045] (NotificationAreaIconRearrange)
Priority        : ImageOverride (15)
State           : Disabled (1)
Type            : Override (0)

[38859191] (RedirectProgrammableTiles)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[38888144] (ASRTest)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[39130862] (FederatedSignInPerfImprovements)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39130896] (LogonWebHostAdditionalMenus)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39139876] (StickersCraftsmanship)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39145991] (NWMTest1)
Priority        : ImageOverride (15)
State           : Enabled (2)
Type            : Override (0)

[39146010] (UxTest12)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[39177456] (MoreProgrammableSlotsInStart)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39281392] (MTestUx13)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[39410888] (CDPNearShareUDPDiscoveryFixup)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

**Comment by thebookisclosed** [comment]
Hi, apologies for the rather late reply.
The help for the /fullreset command states that it leaves priority 0 and 15 configurations alone. These are configured through Windows composition and would require me to fiddle with registry permissions to alter, don't really want to do that.
