### ISSUE TITLE
Drag & Drop problem

### ISSUE THREAD

**Issue by fawzynahwi** [thebookisclosed/ViVe#76]
I am on Win 11 22H2 and after this update I was able to drag and drop to taskbar. I used this service to enable Tabs in Windows explorer using these commands : 
vivetool /enable /id:37634385
vivetool /enable /id:39145991
but after it ( even trying to disable it ) resulted that drag and drop was disabled yet again.
any help would be appreciated

**Comment by thebookisclosed** [comment]
The features you've enabled have nothing to do with taskbar drag and drop. You can try resetting the feature store but there's no guarantee that it will help. What happened sounds more like a coincidence than an effect of manual feature editing.
