### ISSUE TITLE
Fullreset command doesn't work properly

### ISSUE THREAD

**Issue by NuclearMeltdown** [thebookisclosed/ViVe#78]
Hi, whenever I try resetting all of my ViVetool overrides since I forgot which ID's I changed, it just throws me this error: 

"An error occurred while resetting feature configurations in the Runtime store (The parameter is incorrect)"

How can I fix this? I want to go back to default settings since I have a few issues, namely with widgets and taskbar buttons and an in-place upgrade didn't fix them so disabling overrides is my last resort before a clean install. (Also sorry if this is a duplicate issue, but searching github issues didn't come up with anything useful)

Thanks!

**Comment by thebookisclosed** [comment]
Which build of Windows are you using?

**Comment by NuclearMeltdown** [comment]
Right now, 22623.1245. Currently in the windows insider beta branch. Updating to 22623.1250 later today.

**Comment by thebookisclosed** [comment]
Can you confirm that some Priority 9 features show up when you do `/query`?
This is a new reserved priority recently introduced in Dev and I guess it might have made its way to Beta by now. At time of v0.3.2 release only priorities 0 and 15 were considered reserved by the system. An update excluding this priority from management will be needed to make /fullreset work again.

**Comment by NuclearMeltdown** [comment]
Yep, there are a bunch of priority 9 features in the query, I checked that yesterday.

**Comment by pedoc** [comment]
same problem on dev 25295

**Comment by he3als** [comment]
Same problem on stable Win 11 (22621.1265)

**Comment by d123450** [comment]
Same problem on Win11 22621.1265 .  How to fix it?

**Comment by toineenzo** [comment]
Also having the same problem with Windows 11 stable 22621.1344

**Comment by toineenzo** [comment]
This is what I see when I do 'vivetool /query' btw
`
[18299130] (EnableValueBanner)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)

[19638787] (ValueBannerEnableRewards)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)

[23531064] (ShowBrowserOnValueBanner)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
Variant         : 2

[23562335] (DefaultBrowserSettings)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
Variant         : 2

[23563673] (ShowBrowserOnScoobe)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
Variant         : 2

[25704915] (RebootDowntimeEstimate)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
Variant         : 1

[26008830] (STTest)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[26008830] (STTest)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[26008830] (STTest)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[27075521] (ImmersiveShellComponentsInitializationBudget)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)
Variant         : 1
PayloadKind     : Resident (1)
Payload         : 10bd

[32862274] (PISubscriptionFeatureCard)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)

[34300186] (WidgetsExpandedView)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[34592303] (SuggestedActionsOnCopy)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[34592303] (SuggestedActionsOnCopy)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[35620393] (TOTest)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[35620393] (TOTest)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[35681102] (DoNotUseForTesting)
Priority        : Service (4)
State           : Disabled (1)
Type            : Experiment (1)

[36390579] (AdminFlowRejuv_Master)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[36390579] (AdminFlowRejuv_Master)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[36803287] (FetchIrisTriggerJSON)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[36803295] (GetStartedIrisNavMesh)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[36803303] (StaticIrisNavMesh)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[36860984] (Servicing_TaskbarTaskManager_36860984)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[37007953] (PATKTI)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[37007953] (PATKTI)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[37337255] (SmartClipboardUX)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[37337255] (SmartClipboardUX)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[37337272] (SmartWorkflows)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[37482934] (LogonTaskDurationsTIP)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)
Variant         : 1
PayloadKind     : Resident (1)
Payload         : 1e09

[37634385] (TIFE)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[37634385] (TIFE)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[37715785] (ProfileDataRoamingClient11x11)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[37715785] (ProfileDataRoamingClient11x11)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[38266311]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[38320543] (SmartWorkflowsAugLoopTelemetry)
Priority        : ImageOverride (15)
State           : Disabled (1)
Type            : Override (0)

[38665217] (FileExplorerLiveSERP)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[38665217] (FileExplorerLiveSERP)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[38667620] (MoreGraphItems)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[38667620] (MoreGraphItems)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[38758896] (BSFUPP)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[38758896] (BSFUPP)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[38764045] (NotificationAreaIconRearrange)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[38764045] (NotificationAreaIconRearrange)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[38764045] (NotificationAreaIconRearrange)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[38823293] (SettingsRejuv_RepairDarwinApps_Settings)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[38823293] (SettingsRejuv_RepairDarwinApps_Settings)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[38859191] (RedirectProgrammableTiles)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[38859191] (RedirectProgrammableTiles)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[38888144] (ASRTest)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[38888144] (ASRTest)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[38937525] (FindInStart)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[38937525] (FindInStart)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[38937525] (FindInStart)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[38961939]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[39070304]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[39130862] (FederatedSignInPerfImprovements)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[39130862] (FederatedSignInPerfImprovements)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39130896] (LogonWebHostAdditionalMenus)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[39130896] (LogonWebHostAdditionalMenus)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39139876] (StickersCraftsmanship)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[39139876] (StickersCraftsmanship)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39145991] (NWMTest1)
Priority        : ImageOverride (15)
State           : Enabled (2)
Type            : Override (0)

[39146010] (UxTest12)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[39146010] (UxTest12)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[39177456] (MoreProgrammableSlotsInStart)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[39177456] (MoreProgrammableSlotsInStart)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39263329] (SearchBoxPillButton)
Priority        : User (8)
State           : Disabled (1)
Type            : Override (0)

[39263329] (SearchBoxPillButton)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)
Variant         : 1

[39275950] (EnableFedSignInProForEdu)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[39275950] (EnableFedSignInProForEdu)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39281392] (MTestUx13)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[39281392] (MTestUx13)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[39281392] (MTestUx13)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39410888] (CDPNearShareUDPDiscoveryFixup)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[39410888] (CDPNearShareUDPDiscoveryFixup)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39420424] (TaskManagerFilterEngine)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[39420424] (TaskManagerFilterEngine)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[39435873]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39909691]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[40041210]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[40112637]
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[40149356] (FileExplorerHomePageReportFileUsage)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[40149356] (FileExplorerHomePageReportFileUsage)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[40616880] (Servicing_SAC_Telemetry_Rework_40616880)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[40618079] (NarratorNaturalVoiceDialog)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[40618079] (NarratorNaturalVoiceDialog)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[40741162]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[40772499] (FullPageWebXT)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[40867945]
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[40867945]
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[40883769]
Priority        : Service (4)
State           : Disabled (1)
Type            : Experiment (1)

[40887771] (SearchBoxOnTaskbar)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[40887771] (SearchBoxOnTaskbar)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[40887771] (SearchBoxOnTaskbar)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[40981503]
Priority        : Service (4)
State           : Disabled (1)
Type            : Experiment (1)

[40997837]
Priority        : 9
State           : Disabled (1)
Type            : Override (0)

[41137130]
Priority        : Service (4)
State           : Disabled (1)
Type            : Experiment (1)

[41217123]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41292604] (SuggestedActionsOnCopy_EntityActionWISEModel)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41292604] (SuggestedActionsOnCopy_EntityActionWISEModel)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41296717]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41296904]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41309696]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41310288]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41326453]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41326710]
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41326710]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41349906]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41390426]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41410356]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41415839] (DynamicContentInTaskbarSearchBox)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41415839] (DynamicContentInTaskbarSearchBox)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41417401]
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41417401]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41445114] (TKITest2)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41445114] (TKITest2)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41473870]
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41473870]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41534064]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41598133] (AdminFlowRejuv_FeaturedReset)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[41598133] (AdminFlowRejuv_FeaturedReset)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41645378]
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41645378]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41646677]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41655236] (MTestUx14)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41655236] (MTestUx14)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[41738299]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41738346]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[41772259]
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)

[41894767]
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41894767]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41897055]
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41897055]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41932313]
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[41932313]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[42038001]
Priority        : User (8)
State           : Disabled (1)
Type            : Override (0)

[42052423] (ODLogo)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)

[42106010] (SoundOptions)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[42106010] (SoundOptions)
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[42137250]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[42282162]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[42442584]
Priority        : 9
State           : Enabled (2)
Type            : Override (0)

[42606616]
Priority        : Service (4)
State           : Default (0)
Type            : Experiment (1)

[42606616]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[43370230]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)
`

**Comment by thebookisclosed** [comment]
A fix for this issue will be released later this week.

**Comment by thebookisclosed** [comment]
Fixed in v0.3.3 (97195a452776534c2c5973afd5b70e4ac9d3e3a9)

**Comment by toineenzo** [comment]
Works perfectly fine now!

**Comment by 3ogi** [comment]
> Works perfectly fine now!

Can you write the codes ?

**Comment by Jon-David** [comment]
How do I do that? I have version 0.3.2

**Comment by toineenzo** [comment]
> How do I do that? I have version 0.3.2

How about you read and update

**Comment by gredding1986-byte** [comment]
Omlouvám se, Slečno Liduško Bohdanecká, ano ? !
