### ISSUE TITLE
Enable does not work

### ISSUE THREAD

**Issue by gboo14** [thebookisclosed/ViVe#79]
Fix it pls

**Comment by gus33000** [comment]
Could you provide a bit more details? What command are you running, for example:

```vivetool.exe /enable /id:123456789```

what error do you get, what makes you think it didn't work, what os version are you using (for example, Windows 10 build 19042 (can check winver by pressing WIN+R, type 'winver' and show a screenshot, like the one below ⬇️).

![image](https://user-images.githubusercontent.com/3755345/220645590-2043662a-935c-4430-85e1-404a85861a9f.png)

Thank you!
