### ISSUE TITLE
How can I reset this?

### ISSUE THREAD

**Issue by Jon-David** [thebookisclosed/ViVe#83]
Hi. Okay, Today I installed the file 'ViVeTool-v0.3.2.zip' and extracted everything into the created folder 'zVIVE' on the C drive. Then I opened CMD as Administrator and used the commands 'cd C:\zVIVE' and 'vivetool /disable /id:26008830'. I restarted the computer and as expected, it worked. Now I want to go back to how it was before all of this. Is there any method or command I can use?

**Comment by sakmak07** [comment]
im also trying to find a solution to revert the whole thing but still no answer. i regret coming to this in the first place

**Comment by thebookisclosed** [comment]
Extension of #78 which is fixed as of v0.3.3
