### ISSUE TITLE
Commands not working 

### ISSUE THREAD

**Issue by Or-uh** [thebookisclosed/ViVe#85]
I open cmd in admin, go to zVIVE directory, it tells me available commands adn the i try to use any commmand and it tells me                "/disable' is not recognized as an internal or external command, operable program or batch file." I am on windows OS Build 22621.1344

**Comment by thebookisclosed** [comment]
You seem to be following a tutorial and forgetting to start the command with `vivetool` when issuing subcommands such as `/disable`

**Comment by Or-uh** [comment]
i do "cd vivetool" before i do anything if thats what you are referring too

**Comment by thebookisclosed** [comment]
I'm not, I'm talking about the start of a command being the name of the program itself, instead of the slash prefixed subcommand which comes after.
I'd generally advise you against using this tool if you aren't familiar with command line tools.

**Comment by natsteps** [comment]
Hey umm im very confused and im having the same trouble as @Or-uh , idk the commands at all

**Comment by thebookisclosed** [comment]
This is a bug/issue tracker, teaching CLI basics is definitely out of its scope.
