### ISSUE TITLE
[Query] How to use the tool?

### ISSUE THREAD

**Issue by onlytanmoy** [thebookisclosed/ViVe#86]
Hiya, I am following the instructions from here https://beebom.com/how-enable-file-explorer-tabs-windows-11/
but unable to get tabbed browsing enabled for my windows explorer :( 

I am using the latest version ViVeTool-v0.3.3
![image](https://user-images.githubusercontent.com/48493659/227368371-e1e53b58-da22-490c-bd71-1bdd5993c024.png)

Please help.

**Comment by thebookisclosed** [comment]
2262x.1413 should have tabs enabled out of box for virtually everyone, it almost sounds like you've deliberately disabled them earlier. What does `vivetool /query /name:TIFE` output?

**Comment by onlytanmoy** [comment]
Please see output below

D:\Installed Apps\ViVeTool-v0.3.3>vivetool /query /name:TIFE
ViVeTool v0.3.3 - Windows feature configuration tool

[37634385] (TIFE)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

**Comment by thebookisclosed** [comment]
That looks correct, how about `vivetool /query /name:NWMTest1` ?

**Comment by onlytanmoy** [comment]
D:\Installed Apps\ViVeTool-v0.3.3>vivetool /query /name:NWMTest1
ViVeTool v0.3.3 - Windows feature configuration tool

[39145991] (NWMTest1)
Priority        : ImageOverride (15)
State           : Enabled (2)
Type            : Override (0)

**Comment by thebookisclosed** [comment]
The tabs really should be on then, are you maybe using some 3rd party File Explorer modifications? Mind posting a screenshot of the This PC window?

**Comment by onlytanmoy** [comment]
I am using StartAllBack.
![image](https://user-images.githubusercontent.com/48493659/227793983-ee144806-ab22-430b-abee-6decbe81eccb.png)

I have seen the + button to add new tab with a previous version of ViveTool while using StartAllBack.

**Comment by thebookisclosed** [comment]
Do tabs work if you temporarily disable StartAllBack?

**Comment by onlytanmoy** [comment]
Yes, I could then see the + button on the top.

**Comment by thebookisclosed** [comment]
Well then it's not a ViVe issue, more so a third party shell mod issue.
