### ISSUE TITLE
File Explorer Tab Drag and Drop Feature Not Working

### ISSUE THREAD

**Issue by rysci8** [thebookisclosed/ViVe#87]
Despite following all the steps, receiving confirmation from Command Prompt that the ViveTool feature has been successfully configured, dragging tabs onto the desktop does not work. Not exactly sure what other methods I'm supposed to follow.

The steps I took are as follows:
1) Downloaded vivetool-v0.3.3.zip
2) Extracted all 4 files to Windows\System32\
3) Opened Command Prompt using admin privs.
4) Ran the following code: vivetool /enable /id:39661369
5) Command Prompt responds with "Successfully set feature configuration(s"
6) Restarted
7) Attempted to drag file explorer tabs onto desktop and met with the same cancel sign. 

My only assumption is that the id number is wrong since this was the number given for the previous v.0.3.2 version.

**Comment by rysci8** [comment]
Not sure if this helps at all, but I'm including the query line of text:

C:\Windows\System32>vivetool/query
ViVeTool v0.3.3 - Windows feature configuration tool

[19638787] (ValueBannerEnableRewards)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)

[25704915] (RebootDowntimeEstimate)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
Variant         : 1

[26008830] (STTest)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[27075521] (ImmersiveShellComponentsInitializationBudget)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
Variant         : 1
PayloadKind     : Resident (1)
Payload         : 0x10bd

[34592303] (SuggestedActionsOnCopy)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[35620393] (TOTest)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[35681102] (DoNotUseForTesting)
Priority        : Service (4)
State           : Disabled (1)
Type            : Experiment (1)

[36354489] (SV2Navpane)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[36803287] (FetchIrisTriggerJSON)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)

[36803295] (GetStartedIrisNavMesh)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)

[37007953] (PATKTI)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[37337255] (SmartClipboardUX)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[37337272] (SmartWorkflows)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[37482934] (LogonTaskDurationsTIP)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
Variant         : 1
PayloadKind     : Resident (1)
Payload         : 0x1e09

[37634385] (TIFE)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[37634385] (TIFE)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[37715785] (ProfileDataRoamingClient11x11)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[38266311] (MSRC70412_PrintManifestRedirectOptIn)
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[38320543] (SmartWorkflowsAugLoopTelemetry)
Priority        : ImageOverride (15)
State           : Disabled (1)
Type            : Override (0)

[38667620] (MoreGraphItems)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[38758896] (BSFUPP)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[38764045] (NotificationAreaIconRearrange)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[38859191] (RedirectProgrammableTiles)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[38888144] (ASRTest)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[38937525] (FindInStart)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[38961939] (MSRC71279_FixCredPackProtectedFlagUsage)
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[39070304] (MSRC71370_GmsaLogonFix)
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[39130862] (FederatedSignInPerfImprovements)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39130896] (LogonWebHostAdditionalMenus)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39139876] (StickersCraftsmanship)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39145991] (NWMTest1)
Priority        : ImageOverride (15)
State           : Enabled (2)
Type            : Override (0)

[39145991] (NWMTest1)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[39146010] (UxTest12)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[39177456] (MoreProgrammableSlotsInStart)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39263329] (SearchBoxPillButton)
Priority        : Service (4)
State           : Enabled (2)
Type            : Experiment (1)
Variant         : 1

[39275950] (EnableFedSignInProForEdu)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39281392] (MTestUx13)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39410888] (CDPNearShareUDPDiscoveryFixup)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39435873]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[39661369] (FETTOM)
Priority        : User (8)
State           : Enabled (2)
Type            : Override (0)

[39909691]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[40041210] (MSRC72593_SecurityFix)
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[40149356] (FileExplorerHomePageReportFileUsage)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[40616880] (Servicing_SAC_Telemetry_Rework_40616880)
Priority        : Service (4)
State           : Disabled (1)
Type            : Experiment (1)

[40741162]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[40867945] (SearchBoxNQS)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[40883769]
Priority        : Service (4)
State           : Disabled (1)
Type            : Experiment (1)

[40887771] (SearchBoxOnTaskbar)
Priority        : Service (4)
State           : Disabled (1)
Type            : Experiment (1)

[40887771] (SearchBoxOnTaskbar)
Priority        : Safeguard (2)
State           : Disabled (1)
Type            : Experiment (1)

[40887771] (SearchBoxOnTaskbar)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[40981503]
Priority        : Service (4)
State           : Disabled (1)
Type            : Experiment (1)

[40997837]
Priority        : Security (9)
State           : Disabled (1)
Type            : Override (0)

[41137130]
Priority        : Service (4)
State           : Disabled (1)
Type            : Experiment (1)

[41217123] (MSRC74246_Servicing_NTLM_ServiceBinding_ContextSwapping)
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41292604] (SuggestedActionsOnCopy_EntityActionWISEModel)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41296717]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41296904]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41309696]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41310288]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41326453]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41326710] (Servicing_GoLocalGeoMap_41326710)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41349906]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41390426]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41410356]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41415839] (DynamicContentInTaskbarSearchBox)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41417401] (WebView1Sensor)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41445114] (TKITest2)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41473870] (Servicing_WinHttpUsageEnabled_41473870)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41534064]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41645378] (Servicing_AvoidDuplicateCalls_41645378)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41646677]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41655236] (MTestUx14)
Priority        : ImageDefault (0)
State           : Disabled (1)
Type            : Override (0)

[41738299]
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41738346]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[41894767] (Servicing_SendGlobalId_41894767)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41897055] (Servicing_SendUserSid_41897055)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[41932313] (Servicing_MapUrlToZoneEnabled_41932313)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[42077290]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[42137250]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[42282162]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[42442584]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[42606616] (SearchBoxOnTaskbarWave2)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[42621371]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[43370230] (DismissSearchOnDisplayChange)
Priority        : ImageDefault (0)
State           : Enabled (2)
Type            : Override (0)

[43395465]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

[43699671]
Priority        : Security (9)
State           : Enabled (2)
Type            : Override (0)

**Comment by thebookisclosed** [comment]
Are you sure you're using a build that supports this feature?
Also, for future reference - this is a tracker for ViVeTool bugs, not feature override advice.

**Comment by rysci8** [comment]
I'm currently running the latest version of Windows 11, is that incompatible with this tool?

Also, I figured pointing out that if the tool is saying "Successfully set feature configuration(s)" and the feature is not working, that would be classified as a bug.

**Comment by thebookisclosed** [comment]
Feature configurations are conceptually similar to registry edits, you're simply writing an ID and your desired enablement state to a configuration store somewhere. There is no way for the store to know if the system will ever care about the ID you've inserted.
There's a wiki page about this too.
Tab Drag & Drop is only available on insider builds as far as I'm aware.

**Comment by eidrof** [comment]
I had the same problem and my version is
![QQ截图20230628231520](https://github.com/thebookisclosed/ViVe/assets/59110253/690104f6-cc5c-4e18-abb2-c1d803ca0273)
How to solve it? Doesn't my version have this feature either

**Comment by thebookisclosed** [comment]
The feature is not available in zn_release builds.

**Comment by eidrof** [comment]
> 此功能在zn_release版本中不可用。
I really need this feature, which version should I fall back to?

**Comment by thebookisclosed** [comment]
> 此功能在zn_release版本中不可用。
> > I really need this feature, which version should I fall back to?

The recent 234xx ni_prerelease builds should have it. (Dev channel)

**Comment by eidrof** [comment]
I'm going crazy, I'm starting to have the same problem with the owner of this post touching ....
You'll have to look at this
![屏幕截图(3)](https://github.com/thebookisclosed/ViVe/assets/59110253/fef9f335-9192-4383-a7dd-e493a8f4902d)

The same problem, already shown like this↓
[39661369] (FETTOM)
Priority : User (8)
State : Enabled (2)
Type : Override (0)

But the functionality has not changed.....

**Comment by panwanke** [comment]
Same question +1.  

Windows version is 23H2 22635.2483
