### ISSUE TITLE
how to uninstall

### ISSUE THREAD

**Issue by Wiluke** [thebookisclosed/ViVe#88]
how to uninstall?

**Comment by thebookisclosed** [comment]
A multitude of "issues" with this exact same questions have been closed in the past. ViVeTool is a standalone program that doesn't install itself anywhere. You're probably wanting to reset the manual feature overrides you've added using the tool, in which case you're supposed to use the `/fullreset` command.
You really should look into how a tool works before blindly using it and then wondering how to undo changes.
