### ISSUE TITLE
This broke my mic. 

### ISSUE THREAD

**Issue by Harmaasormi** [thebookisclosed/ViVe#90]
Hi. This broke my microphone and now my computer doesn't recognize my microphone or its existence. I just want to play games with my friends again. So I don't know what to do. Previously, a Windows update fixed the issue, but not anymore. So I'm asking for advice on how to fix this.

**Comment by thebookisclosed** [comment]
This has no means of altering your audio config in any way imaginable. How did you even arrive at this conclusion?

**Comment by stretch07** [comment]
lmfao
