### ISSUE TITLE
This version of C:\zVIVE\ViVeTool.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

### ISSUE THREAD

**Issue by 3FrotoDev** [thebookisclosed/ViVe#92]
This version of C:\zVIVE\ViVeTool.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by thebookisclosed** [comment]
The least you could do is download the right version for your architecture. Don't follow tutorials that use tools you don't understand the implications of either.
