### ISSUE TITLE
Not Compatible

### ISSUE THREAD

**Issue by KirovYuri** [thebookisclosed/ViVe#97]
help me this its says here:

This version of C:\zVIVE\ViVeTool.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

![image](https://github.com/thebookisclosed/ViVe/assets/109130619/6e625c4f-4cb0-4619-8a00-eda922ad6188)

**Comment by thebookisclosed** [comment]
Download the right ZIP for your architecture.
