### ISSUE TITLE
hel pleased help add GUI

### ISSUE THREAD

**Issue by fisforfaheem** [thebookisclosed/ViVe#99]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\Faheem> cd "C:\Users\Faheem\Desktop\New folder (4)\ViVeTool.exe"
cd : Cannot find path 'C:\Users\Faheem\Desktop\New folder (4)\ViVeTool.exe' because it does not exist.
At line:1 char:1
+ cd "C:\Users\Faheem\Desktop\New folder (4)\ViVeTool.exe"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Faheem...4)\ViVeTool.exe:String) [Set-Location], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\Faheem> cd "C:\Users\Faheem\Desktop\1111\ViVeTool.exe"
cd : Cannot find path 'C:\Users\Faheem\Desktop\1111\ViVeTool.exe' because it does not exist.
At line:1 char:1
+ cd "C:\Users\Faheem\Desktop\1111\ViVeTool.exe"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Faheem...11\ViVeTool.exe:String) [Set-Location], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\Faheem> ls

    Directory: C:\Users\Faheem

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         4/23/2023   3:30 PM                .android
d-----         7/10/2022  12:36 AM                .gradle
d-----         6/10/2022   5:40 PM                .Ld2VirtualBox
d-----          7/2/2022   4:07 PM                .mume
d-----        10/19/2021   5:35 PM                .rest-client
d-----         4/11/2023  11:32 AM                .vscode-cli
d-----        10/19/2021   5:24 PM                .vscode-insiders
d-----        10/19/2021   8:35 PM                AndroidStudioProjects
d-r---         5/26/2023   1:04 AM                Contacts
d-r---         5/30/2023   2:42 AM                Desktop
d-r---         5/27/2023   5:28 PM                Documents
d-r---         5/28/2023   2:41 AM                Downloads
d-r---         5/26/2023   1:04 AM                Favorites
d-r---         5/26/2023   1:04 AM                Links
d-r---         5/26/2023   1:04 AM                Music
dar--l         1/21/2022   7:50 PM                OneDrive
d-r---         5/27/2023   3:08 PM                Pictures
d-r---         5/26/2023   1:04 AM                Saved Games
d-r---         5/26/2023   1:04 AM                Searches
d-----        10/19/2021   4:28 PM                source
d-r---         5/26/2023   1:04 AM                Videos
-a----         6/10/2022   5:47 PM           6280 -1.14-windows.xml
-a----         7/28/2022   2:51 PM            306 .gitconfig

PS C:\Users\Faheem> cd desktop
PS C:\Users\Faheem\desktop> cd 1111
PS C:\Users\Faheem\desktop\1111> ls

    Directory: C:\Users\Faheem\desktop\1111

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          3/7/2023  10:36 PM          15360 Albacore.ViVe.dll
-a----         3/23/2023   2:11 AM         292881 FeatureDictionary.pfs
-a----          3/8/2023  12:09 PM         711952 Newtonsoft.Json.dll
-a----         3/23/2023   2:35 AM          50688 ViVeTool.exe

PS C:\Users\Faheem\desktop\1111> ViveTool /enable /id:34878152
ViveTool : The term 'ViveTool' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ViveTool /enable /id:34878152
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ViveTool:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Suggestion [3,General]: The command ViveTool was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\ViveTool". See "get-help about_Command_Precedence" for more details.
PS C:\Users\Faheem\desktop\1111> vivetool /disable /id:34878152
vivetool : The term 'vivetool' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ vivetool /disable /id:34878152
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (vivetool:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Suggestion [3,General]: The command vivetool was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\vivetool". See "get-help about_Command_Precedence" for more details.
PS C:\Users\Faheem\desktop\1111> ls

    Directory: C:\Users\Faheem\desktop\1111

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          3/7/2023  10:36 PM          15360 Albacore.ViVe.dll
-a----         3/23/2023   2:11 AM         292881 FeatureDictionary.pfs
-a----          3/8/2023  12:09 PM         711952 Newtonsoft.Json.dll
-a----         3/23/2023   2:35 AM          50688 ViVeTool.exe

PS C:\Users\Faheem\desktop\1111> vive /disable /id:34878152
vive : The term 'vive' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ vive /disable /id:34878152
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (vive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Suggestion [3,General]: The command vive was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\vive". See "get-help about_Command_Precedence" for more details.
PS C:\Users\Faheem\desktop\1111> vive /disable /id:34878152
vive : The term 'vive' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ vive /disable /id:34878152
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (vive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Suggestion [3,General]: The command vive was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\vive". See "get-help about_Command_Precedence" for more details.
PS C:\Users\Faheem\desktop\1111> vive.exe
vive.exe : The term 'vive.exe' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ vive.exe
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (vive.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Suggestion [3,General]: The command vive.exe was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\vive.exe". See "get-help about_Command_Precedence" for more details.
PS C:\Users\Faheem\desktop\1111>

**Comment by daedalusal** [comment]
why are you cd -in an exe file mate cd to the folder you downloaded

**Comment by NotHyper-474** [comment]
You're supposed to use cd with directories, like this: `cd "C:\Users\Faheem\Desktop\New folder (4)\"`
Afterwards you can run the program with `.\ViVeTool.exe`

**Comment by fisforfaheem** [comment]
Please now tell how to revert all changes made by vive, and please do video
tutorials if possible as well



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/13/23,
11:17:50 AM
